CREATE TABLE content_subscription (
  subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_user_id BIGINT NOT NULL,
  trainer_user_id BIGINT NOT NULL,
  tier_id INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT content_subscription_not_self_check CHECK (client_user_id <> trainer_user_id),
  CONSTRAINT content_subscription_tier_fkey
    FOREIGN KEY (trainer_user_id, tier_id)
    REFERENCES content_subscription_tier(trainer_user_id, tier_id)
);

CREATE UNIQUE INDEX content_subscription_active_pair_idx
ON content_subscription(client_user_id, trainer_user_id)
WHERE active;

CREATE INDEX content_subscription_client_idx
ON content_subscription(client_user_id, active, expires_at DESC);

CREATE INDEX content_subscription_trainer_idx
ON content_subscription(trainer_user_id, tier_id);

INSERT INTO content_subscription (
  subscription_id,
  client_user_id,
  trainer_user_id,
  tier_id,
  active,
  expires_at
)
VALUES
  (2401, 1002, 1001, 2, TRUE, now() + INTERVAL '30 days'),
  (2402, 1008, 1004, 2, TRUE, now() + INTERVAL '30 days'),
  (2403, 1009, 1005, 3, TRUE, now() + INTERVAL '30 days')
ON CONFLICT (subscription_id) DO UPDATE
SET client_user_id = EXCLUDED.client_user_id,
    trainer_user_id = EXCLUDED.trainer_user_id,
    tier_id = EXCLUDED.tier_id,
    active = EXCLUDED.active,
    expires_at = EXCLUDED.expires_at,
    updated_at = now();

SELECT setval(
  pg_get_serial_sequence('content_subscription', 'subscription_id'),
  (SELECT GREATEST(COALESCE(MAX(subscription_id), 1), 2403) FROM content_subscription),
  true
);
