CREATE TABLE content_donation (
  donation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id BIGINT NOT NULL,
  recipient_user_id BIGINT NOT NULL,
  amount_value INTEGER NOT NULL CHECK (amount_value > 0),
  currency TEXT NOT NULL CHECK (currency IN ('RUB')),
  message TEXT CHECK (message IS NULL OR char_length(message) <= 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT content_donation_not_self_check CHECK (sender_user_id <> recipient_user_id)
);

CREATE INDEX content_donation_recipient_created_idx
ON content_donation(recipient_user_id, created_at DESC, donation_id DESC);
