package usecase

import "errors"

var (
	ErrInvalidPostID                      = errors.New("invalid post id")
	ErrInvalidUserID                      = errors.New("invalid user id")
	ErrInvalidTitle                       = errors.New("invalid post title")
	ErrInvalidRequiredSubscriptionLevel   = errors.New("invalid required subscription level")
	ErrConflictingSubscriptionLevelUpdate = errors.New("required subscription level and clear flag cannot be used together")
	ErrInvalidSportTypeID                 = errors.New("invalid sport type id")
	ErrConflictingSportTypeUpdate         = errors.New("sport type id and clear flag cannot be used together")
	ErrBlocksRequired                     = errors.New("post blocks are required")
	ErrTooManyBlocks                      = errors.New("too many post blocks")
	ErrReplaceBlocksRequired              = errors.New("replace_blocks must be true when blocks are provided")
	ErrInvalidLimit                       = errors.New("invalid limit")
	ErrInvalidOffset                      = errors.New("invalid offset")
	ErrInvalidSearchFilter                = errors.New("invalid search filter")
	ErrInvalidCommentBody                 = errors.New("invalid comment body")
	ErrPostMediaFileNameRequired          = errors.New("post media file name is required")
	ErrPostMediaContentTypeRequired       = errors.New("post media content type is required")
	ErrPostMediaContentRequired           = errors.New("post media content is required")
	ErrPostMediaTooLarge                  = errors.New("post media file is too large")
	ErrPostMediaContentTypeUnsupported    = errors.New("post media content type is unsupported")
	ErrPostMediaStorageUnavailable        = errors.New("post media storage is unavailable")
	ErrInvalidSubscriptionTierID          = errors.New("invalid subscription tier id")
	ErrInvalidSubscriptionTierName        = errors.New("invalid subscription tier name")
	ErrInvalidSubscriptionTierPrice       = errors.New("invalid subscription tier price")
	ErrInvalidSubscriptionTierDescription = errors.New("invalid subscription tier description")
	ErrConflictingTierDescriptionUpdate   = errors.New("subscription tier description and clear flag cannot be used together")
	ErrInvalidSubscriptionID              = errors.New("invalid subscription id")
	ErrInvalidSubscriptionTarget          = errors.New("invalid subscription target")
	ErrInvalidDonationAmount              = errors.New("invalid donation amount")
	ErrInvalidDonationCurrency            = errors.New("invalid donation currency")
	ErrInvalidDonationMessage             = errors.New("invalid donation message")
	ErrInvalidDonationTarget              = errors.New("invalid donation target")
	ErrInvalidPaymentID                   = errors.New("invalid payment id")
	ErrInvalidPaymentConfirmationToken    = errors.New("invalid payment confirmation token")
	ErrInvalidProviderPaymentID           = errors.New("invalid provider payment id")
	ErrInvalidProviderSubscriptionID      = errors.New("invalid provider subscription id")
	ErrPaymentProviderUnavailable         = errors.New("payment provider is unavailable")
	ErrPaymentNotSucceeded                = errors.New("payment is not succeeded")
	ErrSubscriptionPaymentRequired        = errors.New("subscription payment is required")
	ErrInvalidNotificationID              = errors.New("invalid notification id")
	ErrInvalidNotificationType            = errors.New("invalid notification type")
	ErrInvalidNotificationTitle           = errors.New("invalid notification title")
	ErrInvalidNotificationBody            = errors.New("invalid notification body")
	ErrNotificationPreferencesUnavailable = errors.New("notification preferences storage is unavailable")
	ErrInvalidMeetingWeekday              = errors.New("invalid meeting weekday")
	ErrInvalidMeetingHour                 = errors.New("invalid meeting hour")
	ErrInvalidMeetingTime                 = errors.New("meeting time must be aligned to the start of an hour")
	ErrMeetingTimeInPast                  = errors.New("meeting time must be in the future")
	ErrInvalidMeetingDuration             = errors.New("invalid meeting duration")
	ErrInvalidMeetingRange                = errors.New("invalid meeting date range")
	ErrInvalidMeetingRuleID               = errors.New("invalid meeting rule id")
	ErrInvalidMeetingSlotID               = errors.New("invalid meeting slot id")
	ErrInvalidMeetingBookingID            = errors.New("invalid meeting booking id")
	ErrInvalidMeetingNote                 = errors.New("invalid meeting note")
)
