package usecase

import "errors"

var (
	ErrInvalidPostID                      = errors.New("invalid post id")
	ErrInvalidUserID                      = errors.New("invalid user id")
	ErrInvalidTitle                       = errors.New("invalid post title")
	ErrInvalidRequiredSubscriptionLevel   = errors.New("invalid required subscription level")
	ErrConflictingSubscriptionLevelUpdate = errors.New("required subscription level and clear flag cannot be used together")
	ErrInvalidSportTypeID                 = errors.New("invalid sport type id")
	ErrConflictingSportTypeUpdate         = errors.New("sport type id and clear flag cannot be used together")
	ErrBlocksRequired                     = errors.New("post blocks are required")
	ErrTooManyBlocks                      = errors.New("too many post blocks")
	ErrReplaceBlocksRequired              = errors.New("replace_blocks must be true when blocks are provided")
	ErrInvalidLimit                       = errors.New("invalid limit")
	ErrInvalidOffset                      = errors.New("invalid offset")
	ErrInvalidSearchFilter                = errors.New("invalid search filter")
	ErrInvalidCommentBody                 = errors.New("invalid comment body")
	ErrPostMediaFileNameRequired          = errors.New("post media file name is required")
	ErrPostMediaContentTypeRequired       = errors.New("post media content type is required")
	ErrPostMediaContentRequired           = errors.New("post media content is required")
	ErrPostMediaTooLarge                  = errors.New("post media file is too large")
	ErrPostMediaContentTypeUnsupported    = errors.New("post media content type is unsupported")
	ErrPostMediaStorageUnavailable        = errors.New("post media storage is unavailable")
	ErrInvalidSubscriptionTierID          = errors.New("invalid subscription tier id")
	ErrInvalidSubscriptionTierName        = errors.New("invalid subscription tier name")
	ErrInvalidSubscriptionTierPrice       = errors.New("invalid subscription tier price")
	ErrInvalidSubscriptionTierDescription = errors.New("invalid subscription tier description")
	ErrConflictingTierDescriptionUpdate   = errors.New("subscription tier description and clear flag cannot be used together")
	ErrInvalidSubscriptionID              = errors.New("invalid subscription id")
	ErrInvalidSubscriptionTarget          = errors.New("invalid subscription target")
	ErrInvalidDonationAmount              = errors.New("invalid donation amount")
	ErrInvalidDonationCurrency            = errors.New("invalid donation currency")
	ErrInvalidDonationMessage             = errors.New("invalid donation message")
	ErrInvalidDonationTarget              = errors.New("invalid donation target")
)
