CREATE TYPE attachment_kind AS ENUM ('image', 'video', 'document');
CREATE EXTENSION citext;

CREATE TABLE "user" (
  user_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         citext NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_profile (
  user_id    bigint PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
  username   citext NOT NULL UNIQUE CHECK (username ~ '^[A-Za-z0-9_]{3,30}$');
  first_name text NOT NULL,
  last_name  text NOT NULL,
  bio        text,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admin_profile (
  admin_id   bigint PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trainer_details (
  trainer_user_id         bigint PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
  education_degree        text,
  career_since_date       date CHECK (career_since_date <= CURRENT_DATE)
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE client_details (
  client_id    bigint PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
  fitness_goal text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE session (
  session_id_hash text PRIMARY KEY,
  user_id         bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  expires_at      timestamptz NOT NULL,
  last_seen_at    timestamptz NOT NULL DEFAULT now(),
  revoked_at      timestamptz,
  ip              inet,
  user_agent      text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CHECK (expires_at > created_at)
);

CREATE TABLE sport_type (
  sport_type_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL UNIQUE,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trainer_to_sport_type (
  trainer_id       bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  sport_type_id    bigint NOT NULL REFERENCES sport_type(sport_type_id) ON DELETE CASCADE,
  experience_years integer CHECK (experience_years >= 0),
  sports_rank      text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (trainer_id, sport_type_id)
);

CREATE TABLE subscription_tier (
  subscription_tier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id           bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  title                text NOT NULL,
  description          text,
  price_currency       text NOT NULL,
  price_value          bigint NOT NULL CHECK (price_value >= 0),
  price_exponent       integer NOT NULL CHECK (price_exponent >= 0),
  level_rank           integer NOT NULL CHECK (level_rank > 0),
  is_archived          boolean NOT NULL DEFAULT false,
  archived_at          timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  UNIQUE (trainer_id, level_rank),
);

CREATE TABLE feature_dictionary (
  feature_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code_name    text NOT NULL UNIQUE,
  description  text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE subscription_tier_feature (
  subscription_tier_id bigint NOT NULL REFERENCES subscription_tier(subscription_tier_id) ON DELETE CASCADE,
  feature_id           bigint NOT NULL REFERENCES feature_dictionary(feature_id) ON DELETE CASCADE,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (subscription_tier_id, feature_id)
);

CREATE TABLE user_subscription (
  user_subscription_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_user_id   bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  subscription_tier_id bigint NOT NULL REFERENCES subscription_tier(subscription_tier_id) ON DELETE RESTRICT,
  started_at           timestamptz NOT NULL DEFAULT now(),
  expires_at           timestamptz NOT NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  CHECK (expires_at > started_at)
);

CREATE TABLE post (
  post_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id   bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  min_tier_id  bigint NULL REFERENCES subscription_tier(subscription_tier_id) ON DELETE SET NULL,
  title text NOT NULL,
  text_content text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT post_min_tier_fk
    FOREIGN KEY (trainer_id, min_tier_id)
    REFERENCES subscription_tier (trainer_id, subscription_tier_id)
);

CREATE TABLE post_attachment (
  post_attachment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id            bigint NOT NULL REFERENCES post(post_id) ON DELETE CASCADE,
  file_url           text NOT NULL,
  kind               attachment_kind NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE chat (
  chat_id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id                    bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  trainer_id                   bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  client_last_read_message_id  bigint,
  trainer_last_read_message_id bigint,
  created_at                   timestamptz NOT NULL DEFAULT now(),
  updated_at                   timestamptz NOT NULL DEFAULT now(),

  UNIQUE (client_id, trainer_id),
  CHECK (client_id <> trainer_id)
);

CREATE TABLE message (
  message_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id      bigint NOT NULL REFERENCES chat(chat_id) ON DELETE CASCADE,
  sender_id    bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  text_content text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE chat
  ADD CONSTRAINT chat_client_last_read_fk
  FOREIGN KEY (client_last_read_message_id)
  REFERENCES message(message_id)
  ON DELETE RESTRICT;

ALTER TABLE chat
  ADD CONSTRAINT chat_trainer_last_read_fk
  FOREIGN KEY (trainer_last_read_message_id)
  REFERENCES message(message_id)
  ON DELETE RESTRICT;

CREATE TABLE message_attachment (
  message_attachment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id            bigint NOT NULL REFERENCES message(message_id) ON DELETE CASCADE,
  file_url              text NOT NULL,
  kind                  attachment_kind NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE comment (
  comment_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id           bigint NOT NULL REFERENCES post(post_id) ON DELETE CASCADE,
  author_id         bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  parent_comment_id bigint REFERENCES comment(comment_id) ON DELETE SET NULL,
  text_content      text NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE post_like (
  post_id    bigint NOT NULL REFERENCES post(post_id) ON DELETE CASCADE,
  user_id    bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (post_id, user_id)
);

CREATE TABLE notification (
  notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  is_read         boolean NOT NULL DEFAULT false,
  payload         jsonb NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
