CREATE TYPE attachment_kind AS ENUM ('image', 'video', 'document');
CREATE EXTENSION citext;

CREATE TABLE "user" (
  user_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         citext NOT NULL UNIQUE
                CHECK (char_length(email::text) <= 254),
  password_hash text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_profile (
  user_id    bigint PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
  username   citext NOT NULL UNIQUE CHECK (username ~ '^[A-Za-z0-9_]{3,30}$'),
  first_name text NOT NULL CHECK (char_length(first_name) BETWEEN 1 AND 100),
  last_name  text NOT NULL CHECK (char_length(last_name) BETWEEN 1 AND 100),
  bio        text CHECK (bio IS NULL OR char_length(bio) <= 1000),
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admin_profile (
  admin_id   bigint PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trainer_details (
  trainer_user_id         bigint PRIMARY KEY REFERENCES "user"(user_id) ON DELETE CASCADE,
  education_degree        text CHECK (education_degree IS NULL OR char_length(education_degree) <= 255),
  career_since_date       date CHECK (career_since_date <= CURRENT_DATE),
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE session (
  session_id_hash text PRIMARY KEY,
  user_id         bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  expires_at      timestamptz NOT NULL,
  last_seen_at    timestamptz NOT NULL DEFAULT now(),
  revoked_at      timestamptz,
  ip              inet,
  user_agent      text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CHECK (expires_at > created_at)
);

CREATE TABLE sport_type (
  sport_type_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL UNIQUE,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trainer_to_sport_type (
  trainer_id       bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  sport_type_id    bigint NOT NULL REFERENCES sport_type(sport_type_id) ON DELETE CASCADE,
  experience_years integer CHECK (experience_years >= 0),
  sports_rank      text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (trainer_id, sport_type_id)
);

CREATE TABLE subscription_tier (
  subscription_tier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id           bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  title                text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
  description          text CHECK (description IS NULL OR char_length(description) <= 2000),
  price_currency       text NOT NULL,
  price_value          bigint NOT NULL CHECK (price_value >= 0),
  price_exponent       integer NOT NULL CHECK (price_exponent >= 0),
  level_rank           integer NOT NULL CHECK (level_rank > 0),
  is_archived          boolean NOT NULL DEFAULT false,
  archived_at          timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  UNIQUE (trainer_id, level_rank),
  UNIQUE (trainer_id, subscription_tier_id)
);

CREATE TABLE user_subscription (
  user_subscription_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_user_id   bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  subscription_tier_id bigint NOT NULL REFERENCES subscription_tier(subscription_tier_id) ON DELETE RESTRICT,
  started_at           timestamptz NOT NULL DEFAULT now(),
  expires_at           timestamptz NOT NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),

  CHECK (expires_at > started_at)
);

CREATE TABLE donation (
  donation_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id     bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  recipient_user_id  bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  amount_mantissa    bigint NOT NULL CHECK (amount_mantissa >= 1),
  amount_scale       integer NOT NULL CHECK (amount_scale >= 0),
  currency           text NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  message            text CHECK (message IS NULL OR char_length(message) <= 500),
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),

  CHECK (sender_user_id <> recipient_user_id)
);

CREATE TABLE post (
  post_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trainer_id   bigint NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  min_tier_id  bigint NULL REFERENCES subscription_tier(subscription_tier_id) ON DELETE SET NULL,
  title        text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
  text_content text NOT NULL CHECK (char_length(text_content) BETWEEN 1 AND 10000),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT post_min_tier_fk
    FOREIGN KEY (trainer_id, min_tier_id)
    REFERENCES subscription_tier (trainer_id, subscription_tier_id)
);

CREATE TABLE post_attachment (
  post_attachment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id            bigint NOT NULL REFERENCES post(post_id) ON DELETE CASCADE,
  file_url           text NOT NULL,
  kind               attachment_kind NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
