service_name: content-service

server:
  host: 0.0.0.0
  grpc_port: "9093"
  http_port: "8083"
  shutdown_timeout: 10s

postgres:
  host: localhost
  port: "5432"
  db_name: sporttech_content
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 30m

storage:
  host: localhost
  port: "8000"
  bucket: post-media
  public_base_url: http://localhost:8000/post-media
  use_ssl: false

openapi:
  file_path: grpc/gen/openapiv2/content/v1/content.swagger.json
