-- +goose Up
CREATE TABLE content_payment (
  payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL CHECK (provider IN ('stripe')),
  provider_payment_id TEXT UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('pending', 'confirmed')),
  sender_user_id BIGINT NOT NULL,
  recipient_user_id BIGINT NOT NULL,
  amount_value INTEGER NOT NULL CHECK (amount_value > 0),
  currency TEXT NOT NULL CHECK (currency IN ('RUB')),
  message TEXT CHECK (message IS NULL OR char_length(message) <= 500),
  confirmation_token TEXT NOT NULL UNIQUE,
  confirmation_url TEXT,
  donation_id BIGINT UNIQUE REFERENCES content_donation(donation_id),
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT content_payment_not_self_check CHECK (sender_user_id <> recipient_user_id)
);

CREATE INDEX content_payment_sender_created_idx
ON content_payment(sender_user_id, created_at DESC, payment_id DESC);

CREATE INDEX content_payment_recipient_created_idx
ON content_payment(recipient_user_id, created_at DESC, payment_id DESC);

-- +goose Down
DROP INDEX IF EXISTS content_payment_recipient_created_idx;
DROP INDEX IF EXISTS content_payment_sender_created_idx;
DROP TABLE IF EXISTS content_payment;
