-- +goose Up
CREATE TABLE content_notification (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('comment', 'donation', 'subscription')),
  actor_user_id BIGINT NOT NULL,
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 1000),
  post_id BIGINT REFERENCES content_post(post_id) ON DELETE CASCADE,
  comment_id BIGINT REFERENCES content_comment(comment_id) ON DELETE CASCADE,
  donation_id BIGINT REFERENCES content_donation(donation_id) ON DELETE CASCADE,
  subscription_id BIGINT REFERENCES content_subscription(subscription_id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX content_notification_user_created_idx
ON content_notification(user_id, created_at DESC, notification_id DESC);

CREATE INDEX content_notification_user_unread_idx
ON content_notification(user_id, created_at DESC, notification_id DESC)
WHERE read_at IS NULL;

-- +goose Down
DROP INDEX IF EXISTS content_notification_user_unread_idx;
DROP INDEX IF EXISTS content_notification_user_created_idx;
DROP TABLE IF EXISTS content_notification;
