-- +goose Up
CREATE TYPE content_block_kind AS ENUM ('text', 'image', 'video', 'document');

CREATE TABLE content_post (
  post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_user_id BIGINT NOT NULL,
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
  required_subscription_level INTEGER CHECK (required_subscription_level IS NULL OR required_subscription_level >= 1),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE content_post_block (
  post_block_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES content_post(post_id) ON DELETE CASCADE,
  position INTEGER NOT NULL CHECK (position >= 0),
  kind content_block_kind NOT NULL,
  text_content TEXT,
  file_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT content_post_block_position_key UNIQUE (post_id, position),
  CONSTRAINT content_post_block_payload_check CHECK (
    (kind = 'text' AND text_content IS NOT NULL AND file_url IS NULL)
    OR
    (kind IN ('image', 'video', 'document') AND text_content IS NULL AND file_url IS NOT NULL)
  )
);

CREATE TABLE content_comment (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES content_post(post_id) ON DELETE CASCADE,
  author_user_id BIGINT NOT NULL,
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE content_post_like (
  post_id BIGINT NOT NULL REFERENCES content_post(post_id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  PRIMARY KEY (post_id, user_id)
);

CREATE INDEX content_post_author_created_idx ON content_post(author_user_id, created_at DESC, post_id DESC);
CREATE INDEX content_post_block_post_position_idx ON content_post_block(post_id, position);
CREATE INDEX content_comment_post_created_idx ON content_comment(post_id, created_at ASC, comment_id ASC);
CREATE INDEX content_post_like_post_idx ON content_post_like(post_id);

-- +goose Down
DROP TABLE IF EXISTS content_post_like;
DROP TABLE IF EXISTS content_comment;
DROP TABLE IF EXISTS content_post_block;
DROP TABLE IF EXISTS content_post;
DROP TYPE IF EXISTS content_block_kind;
