CREATE TABLE profile (
  user_id bigint PRIMARY KEY,
  username text NOT NULL CHECK (username ~ '^[A-Za-z0-9_]{3,30}$'),
  first_name text NOT NULL CHECK (char_length(first_name) BETWEEN 1 AND 100),
  last_name text NOT NULL CHECK (char_length(last_name) BETWEEN 1 AND 100),
  bio text CHECK (bio IS NULL OR char_length(bio) <= 1000),
  avatar_url text,
  is_trainer boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT profile_username_key UNIQUE (username)
);

CREATE TABLE trainer_profile (
  user_id bigint PRIMARY KEY REFERENCES profile(user_id) ON DELETE CASCADE,
  education_degree text CHECK (education_degree IS NULL OR char_length(education_degree) <= 255),
  career_since_date date CHECK (career_since_date IS NULL OR career_since_date <= CURRENT_DATE),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sport_type (
  sport_type_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trainer_sport (
  user_id bigint NOT NULL REFERENCES trainer_profile(user_id) ON DELETE CASCADE,
  sport_type_id bigint NOT NULL REFERENCES sport_type(sport_type_id),
  experience_years integer NOT NULL CHECK (experience_years >= 0),
  sports_rank text CHECK (sports_rank IS NULL OR char_length(sports_rank) <= 100),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (user_id, sport_type_id)
);

CREATE INDEX trainer_profile_user_id_idx ON trainer_profile(user_id);
CREATE INDEX trainer_sport_sport_type_id_idx ON trainer_sport(sport_type_id);
