// Code generated by MockGen. DO NOT EDIT.
// Source: content_usecase.go
//
// Generated by this command:
//
//	mockgen -source=content_usecase.go -destination=content_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_SPORT.tech/services/content/internal/domain"
	usecase "github.com/go-park-mail-ru/2026_1_SPORT.tech/services/content/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockContentUseCase is a mock of ContentUseCase interface.
type MockContentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockContentUseCaseMockRecorder
	isgomock struct{}
}

// MockContentUseCaseMockRecorder is the mock recorder for MockContentUseCase.
type MockContentUseCaseMockRecorder struct {
	mock *MockContentUseCase
}

// NewMockContentUseCase creates a new mock instance.
func NewMockContentUseCase(ctrl *gomock.Controller) *MockContentUseCase {
	mock := &MockContentUseCase{ctrl: ctrl}
	mock.recorder = &MockContentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentUseCase) EXPECT() *MockContentUseCaseMockRecorder {
	return m.recorder
}

// CancelSubscription mocks base method.
func (m *MockContentUseCase) CancelSubscription(ctx context.Context, command usecase.CancelSubscriptionCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSubscription", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelSubscription indicates an expected call of CancelSubscription.
func (mr *MockContentUseCaseMockRecorder) CancelSubscription(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSubscription", reflect.TypeOf((*MockContentUseCase)(nil).CancelSubscription), ctx, command)
}

// ConfirmDonationPayment mocks base method.
func (m *MockContentUseCase) ConfirmDonationPayment(ctx context.Context, command usecase.ConfirmDonationPaymentCommand) (domain.DonationPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmDonationPayment", ctx, command)
	ret0, _ := ret[0].(domain.DonationPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmDonationPayment indicates an expected call of ConfirmDonationPayment.
func (mr *MockContentUseCaseMockRecorder) ConfirmDonationPayment(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmDonationPayment", reflect.TypeOf((*MockContentUseCase)(nil).ConfirmDonationPayment), ctx, command)
}

// CreateComment mocks base method.
func (m *MockContentUseCase) CreateComment(ctx context.Context, command usecase.CreateCommentCommand) (domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", ctx, command)
	ret0, _ := ret[0].(domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockContentUseCaseMockRecorder) CreateComment(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockContentUseCase)(nil).CreateComment), ctx, command)
}

// CreateDonationPayment mocks base method.
func (m *MockContentUseCase) CreateDonationPayment(ctx context.Context, command usecase.CreateDonationPaymentCommand) (domain.DonationPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDonationPayment", ctx, command)
	ret0, _ := ret[0].(domain.DonationPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDonationPayment indicates an expected call of CreateDonationPayment.
func (mr *MockContentUseCaseMockRecorder) CreateDonationPayment(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDonationPayment", reflect.TypeOf((*MockContentUseCase)(nil).CreateDonationPayment), ctx, command)
}

// CreatePost mocks base method.
func (m *MockContentUseCase) CreatePost(ctx context.Context, command usecase.CreatePostCommand) (domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, command)
	ret0, _ := ret[0].(domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockContentUseCaseMockRecorder) CreatePost(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockContentUseCase)(nil).CreatePost), ctx, command)
}

// CreateSubscriptionPayment mocks base method.
func (m *MockContentUseCase) CreateSubscriptionPayment(ctx context.Context, command usecase.CreateSubscriptionPaymentCommand) (domain.DonationPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionPayment", ctx, command)
	ret0, _ := ret[0].(domain.DonationPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionPayment indicates an expected call of CreateSubscriptionPayment.
func (mr *MockContentUseCaseMockRecorder) CreateSubscriptionPayment(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionPayment", reflect.TypeOf((*MockContentUseCase)(nil).CreateSubscriptionPayment), ctx, command)
}

// CreateSubscriptionTier mocks base method.
func (m *MockContentUseCase) CreateSubscriptionTier(ctx context.Context, command usecase.CreateSubscriptionTierCommand) (domain.SubscriptionTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptionTier", ctx, command)
	ret0, _ := ret[0].(domain.SubscriptionTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscriptionTier indicates an expected call of CreateSubscriptionTier.
func (mr *MockContentUseCaseMockRecorder) CreateSubscriptionTier(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptionTier", reflect.TypeOf((*MockContentUseCase)(nil).CreateSubscriptionTier), ctx, command)
}

// DeletePost mocks base method.
func (m *MockContentUseCase) DeletePost(ctx context.Context, command usecase.DeletePostCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockContentUseCaseMockRecorder) DeletePost(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockContentUseCase)(nil).DeletePost), ctx, command)
}

// DeleteSubscriptionTier mocks base method.
func (m *MockContentUseCase) DeleteSubscriptionTier(ctx context.Context, command usecase.DeleteSubscriptionTierCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionTier", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptionTier indicates an expected call of DeleteSubscriptionTier.
func (mr *MockContentUseCaseMockRecorder) DeleteSubscriptionTier(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionTier", reflect.TypeOf((*MockContentUseCase)(nil).DeleteSubscriptionTier), ctx, command)
}

// DonateToProfile mocks base method.
func (m *MockContentUseCase) DonateToProfile(ctx context.Context, command usecase.DonateToProfileCommand) (domain.Donation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DonateToProfile", ctx, command)
	ret0, _ := ret[0].(domain.Donation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DonateToProfile indicates an expected call of DonateToProfile.
func (mr *MockContentUseCaseMockRecorder) DonateToProfile(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DonateToProfile", reflect.TypeOf((*MockContentUseCase)(nil).DonateToProfile), ctx, command)
}

// GetBalance mocks base method.
func (m *MockContentUseCase) GetBalance(ctx context.Context, query usecase.GetBalanceQuery) (domain.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, query)
	ret0, _ := ret[0].(domain.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockContentUseCaseMockRecorder) GetBalance(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockContentUseCase)(nil).GetBalance), ctx, query)
}

// GetPost mocks base method.
func (m *MockContentUseCase) GetPost(ctx context.Context, query usecase.GetPostQuery) (domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, query)
	ret0, _ := ret[0].(domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockContentUseCaseMockRecorder) GetPost(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockContentUseCase)(nil).GetPost), ctx, query)
}

// GetTrainerStatistics mocks base method.
func (m *MockContentUseCase) GetTrainerStatistics(ctx context.Context, query usecase.GetTrainerStatisticsQuery) (domain.TrainerStatistics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrainerStatistics", ctx, query)
	ret0, _ := ret[0].(domain.TrainerStatistics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrainerStatistics indicates an expected call of GetTrainerStatistics.
func (mr *MockContentUseCaseMockRecorder) GetTrainerStatistics(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrainerStatistics", reflect.TypeOf((*MockContentUseCase)(nil).GetTrainerStatistics), ctx, query)
}

// LikePost mocks base method.
func (m *MockContentUseCase) LikePost(ctx context.Context, command usecase.LikePostCommand) (domain.PostLikeState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikePost", ctx, command)
	ret0, _ := ret[0].(domain.PostLikeState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikePost indicates an expected call of LikePost.
func (mr *MockContentUseCaseMockRecorder) LikePost(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikePost", reflect.TypeOf((*MockContentUseCase)(nil).LikePost), ctx, command)
}

// ListAuthorPosts mocks base method.
func (m *MockContentUseCase) ListAuthorPosts(ctx context.Context, query usecase.ListAuthorPostsQuery) ([]domain.PostSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuthorPosts", ctx, query)
	ret0, _ := ret[0].([]domain.PostSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuthorPosts indicates an expected call of ListAuthorPosts.
func (mr *MockContentUseCaseMockRecorder) ListAuthorPosts(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuthorPosts", reflect.TypeOf((*MockContentUseCase)(nil).ListAuthorPosts), ctx, query)
}

// ListComments mocks base method.
func (m *MockContentUseCase) ListComments(ctx context.Context, query usecase.ListCommentsQuery) ([]domain.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, query)
	ret0, _ := ret[0].([]domain.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockContentUseCaseMockRecorder) ListComments(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockContentUseCase)(nil).ListComments), ctx, query)
}

// ListMySubscriptions mocks base method.
func (m *MockContentUseCase) ListMySubscriptions(ctx context.Context, query usecase.ListMySubscriptionsQuery) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMySubscriptions", ctx, query)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMySubscriptions indicates an expected call of ListMySubscriptions.
func (mr *MockContentUseCaseMockRecorder) ListMySubscriptions(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMySubscriptions", reflect.TypeOf((*MockContentUseCase)(nil).ListMySubscriptions), ctx, query)
}

// ListNotifications mocks base method.
func (m *MockContentUseCase) ListNotifications(ctx context.Context, query usecase.ListNotificationsQuery) ([]domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, query)
	ret0, _ := ret[0].([]domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockContentUseCaseMockRecorder) ListNotifications(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockContentUseCase)(nil).ListNotifications), ctx, query)
}

// ListPostLikes mocks base method.
func (m *MockContentUseCase) ListPostLikes(ctx context.Context, query usecase.ListPostLikesQuery) ([]domain.PostLike, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPostLikes", ctx, query)
	ret0, _ := ret[0].([]domain.PostLike)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPostLikes indicates an expected call of ListPostLikes.
func (mr *MockContentUseCaseMockRecorder) ListPostLikes(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPostLikes", reflect.TypeOf((*MockContentUseCase)(nil).ListPostLikes), ctx, query)
}

// ListReceivedDonations mocks base method.
func (m *MockContentUseCase) ListReceivedDonations(ctx context.Context, query usecase.ListReceivedDonationsQuery) ([]domain.Donation, int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReceivedDonations", ctx, query)
	ret0, _ := ret[0].([]domain.Donation)
	ret1, _ := ret[1].(int32)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReceivedDonations indicates an expected call of ListReceivedDonations.
func (mr *MockContentUseCaseMockRecorder) ListReceivedDonations(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReceivedDonations", reflect.TypeOf((*MockContentUseCase)(nil).ListReceivedDonations), ctx, query)
}

// ListSubscriptionTiers mocks base method.
func (m *MockContentUseCase) ListSubscriptionTiers(ctx context.Context, query usecase.ListSubscriptionTiersQuery) ([]domain.SubscriptionTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptionTiers", ctx, query)
	ret0, _ := ret[0].([]domain.SubscriptionTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptionTiers indicates an expected call of ListSubscriptionTiers.
func (mr *MockContentUseCaseMockRecorder) ListSubscriptionTiers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptionTiers", reflect.TypeOf((*MockContentUseCase)(nil).ListSubscriptionTiers), ctx, query)
}

// ListTrainerSubscribers mocks base method.
func (m *MockContentUseCase) ListTrainerSubscribers(ctx context.Context, query usecase.ListTrainerSubscribersQuery) ([]domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTrainerSubscribers", ctx, query)
	ret0, _ := ret[0].([]domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTrainerSubscribers indicates an expected call of ListTrainerSubscribers.
func (mr *MockContentUseCaseMockRecorder) ListTrainerSubscribers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTrainerSubscribers", reflect.TypeOf((*MockContentUseCase)(nil).ListTrainerSubscribers), ctx, query)
}

// MarkNotificationRead mocks base method.
func (m *MockContentUseCase) MarkNotificationRead(ctx context.Context, command usecase.MarkNotificationReadCommand) (domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationRead", ctx, command)
	ret0, _ := ret[0].(domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationRead indicates an expected call of MarkNotificationRead.
func (mr *MockContentUseCaseMockRecorder) MarkNotificationRead(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationRead", reflect.TypeOf((*MockContentUseCase)(nil).MarkNotificationRead), ctx, command)
}

// SearchPosts mocks base method.
func (m *MockContentUseCase) SearchPosts(ctx context.Context, query usecase.SearchPostsQuery) ([]domain.PostSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPosts", ctx, query)
	ret0, _ := ret[0].([]domain.PostSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPosts indicates an expected call of SearchPosts.
func (mr *MockContentUseCaseMockRecorder) SearchPosts(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPosts", reflect.TypeOf((*MockContentUseCase)(nil).SearchPosts), ctx, query)
}

// SubscribeToTrainer mocks base method.
func (m *MockContentUseCase) SubscribeToTrainer(ctx context.Context, command usecase.SubscribeToTrainerCommand) (domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeToTrainer", ctx, command)
	ret0, _ := ret[0].(domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeToTrainer indicates an expected call of SubscribeToTrainer.
func (mr *MockContentUseCaseMockRecorder) SubscribeToTrainer(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToTrainer", reflect.TypeOf((*MockContentUseCase)(nil).SubscribeToTrainer), ctx, command)
}

// UnlikePost mocks base method.
func (m *MockContentUseCase) UnlikePost(ctx context.Context, command usecase.LikePostCommand) (domain.PostLikeState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikePost", ctx, command)
	ret0, _ := ret[0].(domain.PostLikeState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlikePost indicates an expected call of UnlikePost.
func (mr *MockContentUseCaseMockRecorder) UnlikePost(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikePost", reflect.TypeOf((*MockContentUseCase)(nil).UnlikePost), ctx, command)
}

// UpdatePost mocks base method.
func (m *MockContentUseCase) UpdatePost(ctx context.Context, command usecase.UpdatePostCommand) (domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", ctx, command)
	ret0, _ := ret[0].(domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockContentUseCaseMockRecorder) UpdatePost(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockContentUseCase)(nil).UpdatePost), ctx, command)
}

// UpdateSubscription mocks base method.
func (m *MockContentUseCase) UpdateSubscription(ctx context.Context, command usecase.UpdateSubscriptionCommand) (domain.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", ctx, command)
	ret0, _ := ret[0].(domain.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockContentUseCaseMockRecorder) UpdateSubscription(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockContentUseCase)(nil).UpdateSubscription), ctx, command)
}

// UpdateSubscriptionTier mocks base method.
func (m *MockContentUseCase) UpdateSubscriptionTier(ctx context.Context, command usecase.UpdateSubscriptionTierCommand) (domain.SubscriptionTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionTier", ctx, command)
	ret0, _ := ret[0].(domain.SubscriptionTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubscriptionTier indicates an expected call of UpdateSubscriptionTier.
func (mr *MockContentUseCaseMockRecorder) UpdateSubscriptionTier(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionTier", reflect.TypeOf((*MockContentUseCase)(nil).UpdateSubscriptionTier), ctx, command)
}

// UploadPostMedia mocks base method.
func (m *MockContentUseCase) UploadPostMedia(ctx context.Context, command usecase.UploadPostMediaCommand) (domain.PostMedia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadPostMedia", ctx, command)
	ret0, _ := ret[0].(domain.PostMedia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadPostMedia indicates an expected call of UploadPostMedia.
func (mr *MockContentUseCaseMockRecorder) UploadPostMedia(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadPostMedia", reflect.TypeOf((*MockContentUseCase)(nil).UploadPostMedia), ctx, command)
}
