service_name: auth-service

server:
  host: 0.0.0.0
  grpc_port: "9091"
  http_port: "8081"
  shutdown_timeout: 10s

postgres:
  host: localhost
  port: "5432"
  db_name: sporttech_auth
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 30m

auth:
  session_ttl: 720h
  bcrypt_cost: 12

openapi:
  file_path: grpc/gen/openapiv2/auth/v1/auth.swagger.json
