// Code generated by MockGen. DO NOT EDIT.
// Source: profile_usecase.go
//
// Generated by this command:
//
//	mockgen -source=profile_usecase.go -destination=profile_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/go-park-mail-ru/2026_1_SPORT.tech/services/profile/internal/domain"
	usecase "github.com/go-park-mail-ru/2026_1_SPORT.tech/services/profile/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileUseCase is a mock of ProfileUseCase interface.
type MockProfileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUseCaseMockRecorder
	isgomock struct{}
}

// MockProfileUseCaseMockRecorder is the mock recorder for MockProfileUseCase.
type MockProfileUseCaseMockRecorder struct {
	mock *MockProfileUseCase
}

// NewMockProfileUseCase creates a new mock instance.
func NewMockProfileUseCase(ctrl *gomock.Controller) *MockProfileUseCase {
	mock := &MockProfileUseCase{ctrl: ctrl}
	mock.recorder = &MockProfileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUseCase) EXPECT() *MockProfileUseCaseMockRecorder {
	return m.recorder
}

// CreateMeasurement mocks base method.
func (m *MockProfileUseCase) CreateMeasurement(ctx context.Context, command usecase.CreateMeasurementCommand) (domain.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeasurement", ctx, command)
	ret0, _ := ret[0].(domain.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeasurement indicates an expected call of CreateMeasurement.
func (mr *MockProfileUseCaseMockRecorder) CreateMeasurement(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeasurement", reflect.TypeOf((*MockProfileUseCase)(nil).CreateMeasurement), ctx, command)
}

// CreateProfile mocks base method.
func (m *MockProfileUseCase) CreateProfile(ctx context.Context, command usecase.CreateProfileCommand) (domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, command)
	ret0, _ := ret[0].(domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileUseCaseMockRecorder) CreateProfile(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileUseCase)(nil).CreateProfile), ctx, command)
}

// DeleteProfile mocks base method.
func (m *MockProfileUseCase) DeleteProfile(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockProfileUseCaseMockRecorder) DeleteProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockProfileUseCase)(nil).DeleteProfile), ctx, userID)
}

// DeleteAvatar mocks base method.
func (m *MockProfileUseCase) DeleteAvatar(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockProfileUseCaseMockRecorder) DeleteAvatar(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockProfileUseCase)(nil).DeleteAvatar), ctx, userID)
}

// DeleteMeasurement mocks base method.
func (m *MockProfileUseCase) DeleteMeasurement(ctx context.Context, command usecase.DeleteMeasurementCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMeasurement", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMeasurement indicates an expected call of DeleteMeasurement.
func (mr *MockProfileUseCaseMockRecorder) DeleteMeasurement(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMeasurement", reflect.TypeOf((*MockProfileUseCase)(nil).DeleteMeasurement), ctx, command)
}

// GetProfile mocks base method.
func (m *MockProfileUseCase) GetProfile(ctx context.Context, userID int64) (domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileUseCaseMockRecorder) GetProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileUseCase)(nil).GetProfile), ctx, userID)
}

// GetProfileByUsername mocks base method.
func (m *MockProfileUseCase) GetProfileByUsername(ctx context.Context, username string) (domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileByUsername", ctx, username)
	ret0, _ := ret[0].(domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileByUsername indicates an expected call of GetProfileByUsername.
func (mr *MockProfileUseCaseMockRecorder) GetProfileByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileByUsername", reflect.TypeOf((*MockProfileUseCase)(nil).GetProfileByUsername), ctx, username)
}

// ListMeasurements mocks base method.
func (m *MockProfileUseCase) ListMeasurements(ctx context.Context, query usecase.ListMeasurementsQuery) ([]domain.Measurement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMeasurements", ctx, query)
	ret0, _ := ret[0].([]domain.Measurement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMeasurements indicates an expected call of ListMeasurements.
func (mr *MockProfileUseCaseMockRecorder) ListMeasurements(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMeasurements", reflect.TypeOf((*MockProfileUseCase)(nil).ListMeasurements), ctx, query)
}

// ListSportTypes mocks base method.
func (m *MockProfileUseCase) ListSportTypes(ctx context.Context) ([]domain.SportType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSportTypes", ctx)
	ret0, _ := ret[0].([]domain.SportType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSportTypes indicates an expected call of ListSportTypes.
func (mr *MockProfileUseCaseMockRecorder) ListSportTypes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSportTypes", reflect.TypeOf((*MockProfileUseCase)(nil).ListSportTypes), ctx)
}

// SearchAuthors mocks base method.
func (m *MockProfileUseCase) SearchAuthors(ctx context.Context, query usecase.SearchAuthorsQuery) ([]domain.AuthorSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAuthors", ctx, query)
	ret0, _ := ret[0].([]domain.AuthorSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAuthors indicates an expected call of SearchAuthors.
func (mr *MockProfileUseCaseMockRecorder) SearchAuthors(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAuthors", reflect.TypeOf((*MockProfileUseCase)(nil).SearchAuthors), ctx, query)
}

// UpdateProfile mocks base method.
func (m *MockProfileUseCase) UpdateProfile(ctx context.Context, command usecase.UpdateProfileCommand) (domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, command)
	ret0, _ := ret[0].(domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileUseCaseMockRecorder) UpdateProfile(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileUseCase)(nil).UpdateProfile), ctx, command)
}

// UploadAvatar mocks base method.
func (m *MockProfileUseCase) UploadAvatar(ctx context.Context, command usecase.UploadAvatarCommand) (domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, command)
	ret0, _ := ret[0].(domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockProfileUseCaseMockRecorder) UploadAvatar(ctx, command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockProfileUseCase)(nil).UploadAvatar), ctx, command)
}
