service_name: api-gateway

server:
  host: 0.0.0.0
  grpc_port: "9090"
  http_port: "8080"
  shutdown_timeout: 10s

downstream:
  auth_grpc_endpoint: localhost:9091
  profile_grpc_endpoint: localhost:9092
  content_grpc_endpoint: localhost:9093

openapi:
  gateway_file_path: grpc/gen/openapiv2/gateway/v1/gateway.swagger.json
