// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package stripe

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientStripe(in *jlexer.Lexer, out *checkoutSessionResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "payment_status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PaymentStatus = string(in.String())
			}
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientStripe(out *jwriter.Writer, in checkoutSessionResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"payment_status\":"
		out.RawString(prefix)
		out.String(string(in.PaymentStatus))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

func (v checkoutSessionResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientStripe(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

func (v checkoutSessionResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientStripe(w, v)
}

func (v *checkoutSessionResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientStripe(&r, v)
	return r.Error()
}

func (v *checkoutSessionResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientStripe(l, v)
}
