--
-- PostgreSQL database dump
--

\restrict NbYcazglNvWJLWs0FlevzaVd2P3VHZLdsjcmbTGl1NndzOeIwnVO4NCYQZaPKXi

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg13+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_stat_statements; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;


--
-- Name: EXTENSION pg_stat_statements; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_stat_statements IS 'track planning and execution statistics of all SQL statements executed';


--
-- Name: content_block_kind; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.content_block_kind AS ENUM (
    'text',
    'image',
    'video',
    'document'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: content_chat_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_chat_message (
    message_id bigint NOT NULL,
    sender_user_id bigint NOT NULL,
    receiver_user_id bigint NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    CONSTRAINT content_chat_message_body_check CHECK (((char_length(body) >= 1) AND (char_length(body) <= 4000)))
);


--
-- Name: content_chat_message_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.content_chat_message_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: content_chat_message_message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.content_chat_message_message_id_seq OWNED BY public.content_chat_message.message_id;


--
-- Name: content_comment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_comment (
    comment_id bigint NOT NULL,
    post_id bigint NOT NULL,
    author_user_id bigint NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT content_comment_body_check CHECK (((char_length(body) >= 1) AND (char_length(body) <= 2000)))
);


--
-- Name: content_comment_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_comment ALTER COLUMN comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_comment_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_donation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_donation (
    donation_id bigint NOT NULL,
    sender_user_id bigint NOT NULL,
    recipient_user_id bigint NOT NULL,
    amount_value integer NOT NULL,
    currency text NOT NULL,
    message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT content_donation_amount_value_check CHECK ((amount_value > 0)),
    CONSTRAINT content_donation_currency_check CHECK ((currency = 'RUB'::text)),
    CONSTRAINT content_donation_message_check CHECK (((message IS NULL) OR (char_length(message) <= 500))),
    CONSTRAINT content_donation_not_self_check CHECK ((sender_user_id <> recipient_user_id))
);


--
-- Name: content_donation_donation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_donation ALTER COLUMN donation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_donation_donation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_meeting_availability_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_meeting_availability_rule (
    rule_id bigint NOT NULL,
    trainer_user_id bigint NOT NULL,
    weekday smallint NOT NULL,
    start_hour smallint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT content_meeting_availability_rule_start_hour_check CHECK (((start_hour >= 0) AND (start_hour <= 23))),
    CONSTRAINT content_meeting_availability_rule_weekday_check CHECK (((weekday >= 0) AND (weekday <= 6)))
);


--
-- Name: content_meeting_availability_rule_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.content_meeting_availability_rule_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: content_meeting_availability_rule_rule_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.content_meeting_availability_rule_rule_id_seq OWNED BY public.content_meeting_availability_rule.rule_id;


--
-- Name: content_meeting_booking; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_meeting_booking (
    booking_id bigint NOT NULL,
    trainer_user_id bigint NOT NULL,
    client_user_id bigint NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NOT NULL,
    status text DEFAULT 'confirmed'::text NOT NULL,
    created_by_user_id bigint NOT NULL,
    note text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    cancelled_at timestamp with time zone,
    cancelled_by_user_id bigint,
    CONSTRAINT content_meeting_booking_check CHECK ((ends_at > starts_at)),
    CONSTRAINT content_meeting_booking_note_check CHECK (((note IS NULL) OR ((char_length(note) >= 1) AND (char_length(note) <= 1000)))),
    CONSTRAINT content_meeting_booking_status_check CHECK ((status = ANY (ARRAY['confirmed'::text, 'cancelled'::text])))
);


--
-- Name: content_meeting_booking_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.content_meeting_booking_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: content_meeting_booking_booking_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.content_meeting_booking_booking_id_seq OWNED BY public.content_meeting_booking.booking_id;


--
-- Name: content_meeting_slot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_meeting_slot (
    slot_id bigint NOT NULL,
    trainer_user_id bigint NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: content_meeting_slot_slot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.content_meeting_slot_slot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: content_meeting_slot_slot_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.content_meeting_slot_slot_id_seq OWNED BY public.content_meeting_slot.slot_id;


--
-- Name: content_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_notification (
    notification_id bigint NOT NULL,
    user_id bigint NOT NULL,
    type text NOT NULL,
    actor_user_id bigint NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    post_id bigint,
    comment_id bigint,
    donation_id bigint,
    subscription_id bigint,
    read_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT content_notification_body_check CHECK (((char_length(body) >= 1) AND (char_length(body) <= 1000))),
    CONSTRAINT content_notification_title_check CHECK (((char_length(title) >= 1) AND (char_length(title) <= 200))),
    CONSTRAINT content_notification_type_check CHECK ((type = ANY (ARRAY['comment'::text, 'donation'::text, 'like'::text, 'post'::text, 'subscription'::text, 'meeting'::text])))
);


--
-- Name: content_notification_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_notification ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_notification_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_payment (
    payment_id bigint NOT NULL,
    provider text NOT NULL,
    provider_payment_id text,
    status text NOT NULL,
    sender_user_id bigint NOT NULL,
    recipient_user_id bigint NOT NULL,
    amount_value integer NOT NULL,
    currency text NOT NULL,
    message text,
    confirmation_token text NOT NULL,
    confirmation_url text,
    tier_id bigint,
    donation_id bigint,
    subscription_id bigint,
    confirmed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT content_payment_amount_value_check CHECK ((amount_value > 0)),
    CONSTRAINT content_payment_currency_check CHECK ((currency = 'RUB'::text)),
    CONSTRAINT content_payment_message_check CHECK (((message IS NULL) OR (char_length(message) <= 500))),
    CONSTRAINT content_payment_not_self_check CHECK ((sender_user_id <> recipient_user_id)),
    CONSTRAINT content_payment_provider_check CHECK ((provider = 'stripe'::text)),
    CONSTRAINT content_payment_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'canceled'::text, 'failed'::text, 'expired'::text])))
);


--
-- Name: content_payment_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_payment ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_payment_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_post (
    post_id bigint NOT NULL,
    author_user_id bigint NOT NULL,
    title text NOT NULL,
    required_subscription_level integer,
    sport_type_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_pinned boolean DEFAULT false NOT NULL,
    CONSTRAINT content_post_required_subscription_level_check CHECK (((required_subscription_level IS NULL) OR (required_subscription_level >= 1))),
    CONSTRAINT content_post_title_check CHECK (((char_length(title) >= 1) AND (char_length(title) <= 200)))
);


--
-- Name: content_post_block; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_post_block (
    post_block_id bigint NOT NULL,
    post_id bigint NOT NULL,
    "position" integer NOT NULL,
    kind public.content_block_kind NOT NULL,
    text_content text,
    file_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT content_post_block_payload_check CHECK ((((kind = 'text'::public.content_block_kind) AND (text_content IS NOT NULL) AND (file_url IS NULL)) OR ((kind = ANY (ARRAY['image'::public.content_block_kind, 'video'::public.content_block_kind, 'document'::public.content_block_kind])) AND (text_content IS NULL) AND (file_url IS NOT NULL)))),
    CONSTRAINT content_post_block_position_check CHECK (("position" >= 0))
);


--
-- Name: content_post_block_post_block_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_post_block ALTER COLUMN post_block_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_post_block_post_block_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_post_like; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_post_like (
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: content_post_post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_post ALTER COLUMN post_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_post_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_post_sport_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_post_sport_type (
    post_id bigint NOT NULL,
    sport_type_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: content_subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_subscription (
    subscription_id bigint NOT NULL,
    client_user_id bigint NOT NULL,
    trainer_user_id bigint NOT NULL,
    tier_id integer NOT NULL,
    active boolean DEFAULT true NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    stripe_subscription_id text,
    current_period_end timestamp with time zone,
    auto_renew boolean DEFAULT false NOT NULL,
    tier_name_snapshot text NOT NULL,
    price_snapshot integer NOT NULL,
    price_change_requires_resubscribe boolean DEFAULT false NOT NULL,
    CONSTRAINT content_subscription_not_self_check CHECK ((client_user_id <> trainer_user_id)),
    CONSTRAINT content_subscription_price_snapshot_non_negative CHECK ((price_snapshot >= 0))
);


--
-- Name: content_subscription_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_subscription ALTER COLUMN subscription_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_subscription_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_subscription_tier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_subscription_tier (
    trainer_user_id bigint NOT NULL,
    tier_id integer NOT NULL,
    name text NOT NULL,
    price integer NOT NULL,
    description text,
    chat_enabled boolean DEFAULT false NOT NULL,
    calendar_enabled boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT content_subscription_tier_description_check CHECK (((description IS NULL) OR (char_length(description) <= 500))),
    CONSTRAINT content_subscription_tier_name_check CHECK (((char_length(name) >= 1) AND (char_length(name) <= 80))),
    CONSTRAINT content_subscription_tier_price_check CHECK ((price >= 0)),
    CONSTRAINT content_subscription_tier_tier_id_check CHECK ((tier_id >= 1))
);


--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goose_db_version (
    id bigint NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now()
);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.goose_db_version_id_seq OWNED BY public.goose_db_version.id;


--
-- Name: notification_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_preferences (
    user_id bigint NOT NULL,
    comments boolean DEFAULT true NOT NULL,
    likes boolean DEFAULT true NOT NULL,
    donations boolean DEFAULT true NOT NULL,
    posts boolean DEFAULT true NOT NULL,
    subscriptions boolean DEFAULT true NOT NULL,
    meetings boolean DEFAULT true NOT NULL,
    email_digest boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: content_chat_message message_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_chat_message ALTER COLUMN message_id SET DEFAULT nextval('public.content_chat_message_message_id_seq'::regclass);


--
-- Name: content_meeting_availability_rule rule_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_meeting_availability_rule ALTER COLUMN rule_id SET DEFAULT nextval('public.content_meeting_availability_rule_rule_id_seq'::regclass);


--
-- Name: content_meeting_booking booking_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_meeting_booking ALTER COLUMN booking_id SET DEFAULT nextval('public.content_meeting_booking_booking_id_seq'::regclass);


--
-- Name: content_meeting_slot slot_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_meeting_slot ALTER COLUMN slot_id SET DEFAULT nextval('public.content_meeting_slot_slot_id_seq'::regclass);


--
-- Name: goose_db_version id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version ALTER COLUMN id SET DEFAULT nextval('public.goose_db_version_id_seq'::regclass);


--
-- Name: content_chat_message content_chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_chat_message
    ADD CONSTRAINT content_chat_message_pkey PRIMARY KEY (message_id);


--
-- Name: content_comment content_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_comment
    ADD CONSTRAINT content_comment_pkey PRIMARY KEY (comment_id);


--
-- Name: content_donation content_donation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_donation
    ADD CONSTRAINT content_donation_pkey PRIMARY KEY (donation_id);


--
-- Name: content_meeting_availability_rule content_meeting_availability__trainer_user_id_weekday_start_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_meeting_availability_rule
    ADD CONSTRAINT content_meeting_availability__trainer_user_id_weekday_start_key UNIQUE (trainer_user_id, weekday, start_hour);


--
-- Name: content_meeting_availability_rule content_meeting_availability_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_meeting_availability_rule
    ADD CONSTRAINT content_meeting_availability_rule_pkey PRIMARY KEY (rule_id);


--
-- Name: content_meeting_booking content_meeting_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_meeting_booking
    ADD CONSTRAINT content_meeting_booking_pkey PRIMARY KEY (booking_id);


--
-- Name: content_meeting_slot content_meeting_slot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_meeting_slot
    ADD CONSTRAINT content_meeting_slot_pkey PRIMARY KEY (slot_id);


--
-- Name: content_meeting_slot content_meeting_slot_trainer_user_id_starts_at_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_meeting_slot
    ADD CONSTRAINT content_meeting_slot_trainer_user_id_starts_at_key UNIQUE (trainer_user_id, starts_at);


--
-- Name: content_notification content_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_notification
    ADD CONSTRAINT content_notification_pkey PRIMARY KEY (notification_id);


--
-- Name: content_payment content_payment_confirmation_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_payment
    ADD CONSTRAINT content_payment_confirmation_token_key UNIQUE (confirmation_token);


--
-- Name: content_payment content_payment_donation_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_payment
    ADD CONSTRAINT content_payment_donation_id_key UNIQUE (donation_id);


--
-- Name: content_payment content_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_payment
    ADD CONSTRAINT content_payment_pkey PRIMARY KEY (payment_id);


--
-- Name: content_payment content_payment_provider_payment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_payment
    ADD CONSTRAINT content_payment_provider_payment_id_key UNIQUE (provider_payment_id);


--
-- Name: content_post_block content_post_block_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_block
    ADD CONSTRAINT content_post_block_pkey PRIMARY KEY (post_block_id);


--
-- Name: content_post_block content_post_block_position_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_block
    ADD CONSTRAINT content_post_block_position_key UNIQUE (post_id, "position");


--
-- Name: content_post_like content_post_like_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_like
    ADD CONSTRAINT content_post_like_pkey PRIMARY KEY (post_id, user_id);


--
-- Name: content_post content_post_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post
    ADD CONSTRAINT content_post_pkey PRIMARY KEY (post_id);


--
-- Name: content_post_sport_type content_post_sport_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_sport_type
    ADD CONSTRAINT content_post_sport_type_pkey PRIMARY KEY (post_id, sport_type_id);


--
-- Name: content_subscription content_subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_subscription
    ADD CONSTRAINT content_subscription_pkey PRIMARY KEY (subscription_id);


--
-- Name: content_subscription_tier content_subscription_tier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_subscription_tier
    ADD CONSTRAINT content_subscription_tier_pkey PRIMARY KEY (trainer_user_id, tier_id);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: notification_preferences notification_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id);


--
-- Name: content_chat_message_conversation_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_chat_message_conversation_idx ON public.content_chat_message USING btree (LEAST(sender_user_id, receiver_user_id), GREATEST(sender_user_id, receiver_user_id), created_at DESC);


--
-- Name: content_chat_message_receiver_unread_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_chat_message_receiver_unread_idx ON public.content_chat_message USING btree (receiver_user_id, is_read) WHERE (is_read = false);


--
-- Name: content_comment_post_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_comment_post_created_idx ON public.content_comment USING btree (post_id, created_at, comment_id);


--
-- Name: content_donation_recipient_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_donation_recipient_created_idx ON public.content_donation USING btree (recipient_user_id, created_at DESC, donation_id DESC);


--
-- Name: content_meeting_booking_client_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_meeting_booking_client_idx ON public.content_meeting_booking USING btree (client_user_id, starts_at);


--
-- Name: content_meeting_booking_trainer_range_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_meeting_booking_trainer_range_idx ON public.content_meeting_booking USING btree (trainer_user_id, starts_at, ends_at) WHERE (status = 'confirmed'::text);


--
-- Name: content_meeting_booking_trainer_start_unique_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX content_meeting_booking_trainer_start_unique_idx ON public.content_meeting_booking USING btree (trainer_user_id, starts_at) WHERE (status = 'confirmed'::text);


--
-- Name: content_meeting_slot_trainer_starts_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_meeting_slot_trainer_starts_idx ON public.content_meeting_slot USING btree (trainer_user_id, starts_at);


--
-- Name: content_notification_like_unique_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX content_notification_like_unique_idx ON public.content_notification USING btree (user_id, actor_user_id, post_id) WHERE ((type = 'like'::text) AND (post_id IS NOT NULL));


--
-- Name: content_notification_user_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_notification_user_created_idx ON public.content_notification USING btree (user_id, created_at DESC, notification_id DESC);


--
-- Name: content_notification_user_unread_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_notification_user_unread_idx ON public.content_notification USING btree (user_id, created_at DESC, notification_id DESC) WHERE (read_at IS NULL);


--
-- Name: content_payment_recipient_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_payment_recipient_created_idx ON public.content_payment USING btree (recipient_user_id, created_at DESC, payment_id DESC);


--
-- Name: content_payment_sender_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_payment_sender_created_idx ON public.content_payment USING btree (sender_user_id, created_at DESC, payment_id DESC);


--
-- Name: content_post_author_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_post_author_created_idx ON public.content_post USING btree (author_user_id, created_at DESC, post_id DESC);


--
-- Name: content_post_block_post_position_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_post_block_post_position_idx ON public.content_post_block USING btree (post_id, "position");


--
-- Name: content_post_like_post_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_post_like_post_idx ON public.content_post_like USING btree (post_id);


--
-- Name: content_post_one_pinned_per_author; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX content_post_one_pinned_per_author ON public.content_post USING btree (author_user_id) WHERE is_pinned;


--
-- Name: content_post_sport_type_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_post_sport_type_id_idx ON public.content_post USING btree (sport_type_id);


--
-- Name: content_post_sport_type_sport_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_post_sport_type_sport_idx ON public.content_post_sport_type USING btree (sport_type_id, post_id);


--
-- Name: content_subscription_active_pair_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX content_subscription_active_pair_idx ON public.content_subscription USING btree (client_user_id, trainer_user_id) WHERE active;


--
-- Name: content_subscription_client_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_subscription_client_idx ON public.content_subscription USING btree (client_user_id, active, expires_at DESC);


--
-- Name: content_subscription_stripe_subscription_id_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX content_subscription_stripe_subscription_id_key ON public.content_subscription USING btree (stripe_subscription_id) WHERE (stripe_subscription_id IS NOT NULL);


--
-- Name: content_subscription_trainer_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX content_subscription_trainer_idx ON public.content_subscription USING btree (trainer_user_id, tier_id);


--
-- Name: content_comment content_comment_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_comment
    ADD CONSTRAINT content_comment_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.content_post(post_id) ON DELETE CASCADE;


--
-- Name: content_notification content_notification_comment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_notification
    ADD CONSTRAINT content_notification_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES public.content_comment(comment_id) ON DELETE CASCADE;


--
-- Name: content_notification content_notification_donation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_notification
    ADD CONSTRAINT content_notification_donation_id_fkey FOREIGN KEY (donation_id) REFERENCES public.content_donation(donation_id) ON DELETE CASCADE;


--
-- Name: content_notification content_notification_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_notification
    ADD CONSTRAINT content_notification_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.content_post(post_id) ON DELETE CASCADE;


--
-- Name: content_notification content_notification_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_notification
    ADD CONSTRAINT content_notification_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.content_subscription(subscription_id) ON DELETE CASCADE;


--
-- Name: content_payment content_payment_donation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_payment
    ADD CONSTRAINT content_payment_donation_id_fkey FOREIGN KEY (donation_id) REFERENCES public.content_donation(donation_id);


--
-- Name: content_payment content_payment_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_payment
    ADD CONSTRAINT content_payment_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.content_subscription(subscription_id);


--
-- Name: content_post_block content_post_block_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_block
    ADD CONSTRAINT content_post_block_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.content_post(post_id) ON DELETE CASCADE;


--
-- Name: content_post_like content_post_like_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_like
    ADD CONSTRAINT content_post_like_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.content_post(post_id) ON DELETE CASCADE;


--
-- Name: content_post content_post_required_subscription_tier_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post
    ADD CONSTRAINT content_post_required_subscription_tier_fkey FOREIGN KEY (author_user_id, required_subscription_level) REFERENCES public.content_subscription_tier(trainer_user_id, tier_id);


--
-- Name: content_post_sport_type content_post_sport_type_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_post_sport_type
    ADD CONSTRAINT content_post_sport_type_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.content_post(post_id) ON DELETE CASCADE;


--
-- Name: content_subscription content_subscription_tier_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_subscription
    ADD CONSTRAINT content_subscription_tier_fkey FOREIGN KEY (trainer_user_id, tier_id) REFERENCES public.content_subscription_tier(trainer_user_id, tier_id);


--
-- PostgreSQL database dump complete
--

\unrestrict NbYcazglNvWJLWs0FlevzaVd2P3VHZLdsjcmbTGl1NndzOeIwnVO4NCYQZaPKXi

