-- +goose Up
CREATE TABLE measurement (
    measurement_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint NOT NULL REFERENCES profile(user_id) ON DELETE CASCADE,
    measured_at     date NOT NULL,
    weight_kg       numeric(5,2) CHECK (weight_kg IS NULL OR weight_kg > 0),
    body_fat_pct    numeric(4,1) CHECK (body_fat_pct IS NULL OR (body_fat_pct >= 0 AND body_fat_pct <= 100)),
    chest_cm        integer CHECK (chest_cm IS NULL OR chest_cm > 0),
    waist_cm        integer CHECK (waist_cm IS NULL OR waist_cm > 0),
    hips_cm         integer CHECK (hips_cm IS NULL OR hips_cm > 0),
    notes           text CHECK (notes IS NULL OR char_length(notes) <= 500),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX measurement_user_id_measured_at_idx ON measurement(user_id, measured_at DESC);

-- +goose Down
DROP TABLE IF EXISTS measurement;
