

\connect sporttech_auth

CREATE TABLE auth_user (
  user_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         text   NOT NULL CHECK (char_length(email) <= 254),
  username      text   NOT NULL CHECK (username ~ '^[A-Za-z0-9_]{3,30}$'),
  password_hash text   NOT NULL,
  role          text   NOT NULL CHECK (role IN ('client', 'trainer', 'admin')),
  status        text   NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT auth_user_email_key    UNIQUE (email),
  CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE auth_session (
  session_id_hash text PRIMARY KEY,
  user_id         bigint NOT NULL REFERENCES auth_user(user_id) ON DELETE CASCADE,
  expires_at      timestamptz NOT NULL,
  revoked_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CHECK (expires_at > created_at)
);

CREATE INDEX auth_session_user_id_idx    ON auth_session(user_id);
CREATE INDEX auth_session_expires_at_idx ON auth_session(expires_at);

INSERT INTO auth_user (user_id, email, username, password_hash, role, status)
VALUES
  (1001, 'anna.coach@sporttech.local',  'coach_anna',      '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'trainer', 'active'),
  (1002, 'ivan.runner@sporttech.local', 'runner_ivan',     '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'client',  'active'),
  (1003, 'mike.swim@sporttech.local',   'swim_mike',       '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'trainer', 'active'),
  (1004, 'elena.yoga@sporttech.local',  'yoga_elena',      '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'trainer', 'active'),
  (1005, 'sergey.box@sporttech.local',  'box_sergey',      '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'trainer', 'active'),
  (1006, 'olga.fit@sporttech.local',    'fit_olga',        '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'trainer', 'active'),
  (1007, 'dima.cycle@sporttech.local',  'cycle_dima',      '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'trainer', 'active'),
  (1008, 'maria.client@sporttech.local','client_maria',    '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'client',  'active'),
  (1009, 'pavel.client@sporttech.local','client_pavel',    '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'client',  'active'),
  (1010, 'admin@sporttech.local',       'admin_sporttech', '$2a$10$wyfCWjNi8FUDZt10JYydtON/VIMO2IsbMaQGzkj5QsT47DIpHeW6W', 'admin',   'active');

SELECT setval(
  pg_get_serial_sequence('auth_user', 'user_id'),
  (SELECT GREATEST(COALESCE(MAX(user_id), 1), 1010) FROM auth_user),
  true
);

CREATE TABLE goose_db_version (
  id         bigserial    NOT NULL PRIMARY KEY,
  version_id bigint       NOT NULL,
  is_applied boolean      NOT NULL,
  tstamp     timestamp    DEFAULT now()
);

INSERT INTO goose_db_version (version_id, is_applied) VALUES
  (0, true),
  (1, true),
  (2, true),
  (3, true);

\connect sporttech_profile

CREATE TABLE profile (
  user_id    bigint PRIMARY KEY,
  username   text   NOT NULL CHECK (username ~ '^[A-Za-z0-9_]{3,30}$'),
  first_name text   NOT NULL CHECK (char_length(first_name) BETWEEN 1 AND 100),
  last_name  text   NOT NULL CHECK (char_length(last_name)  BETWEEN 1 AND 100),
  bio        text   CHECK (bio IS NULL OR char_length(bio) <= 1000),
  avatar_url text,
  is_trainer boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT profile_username_key UNIQUE (username)
);

CREATE TABLE trainer_profile (
  user_id            bigint PRIMARY KEY REFERENCES profile(user_id) ON DELETE CASCADE,
  education_degree   text CHECK (education_degree IS NULL OR char_length(education_degree) <= 255),
  career_since_date  date CHECK (career_since_date IS NULL OR career_since_date <= CURRENT_DATE),
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sport_type (
  sport_type_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text   NOT NULL UNIQUE,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE trainer_sport (
  user_id          bigint  NOT NULL REFERENCES trainer_profile(user_id) ON DELETE CASCADE,
  sport_type_id    bigint  NOT NULL REFERENCES sport_type(sport_type_id),
  experience_years integer NOT NULL CHECK (experience_years >= 0),
  sports_rank      text    CHECK (sports_rank IS NULL OR char_length(sports_rank) <= 100),
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (user_id, sport_type_id)
);

CREATE TABLE measurement (
  measurement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        bigint     NOT NULL REFERENCES profile(user_id) ON DELETE CASCADE,
  measured_at    date       NOT NULL,
  weight_kg      numeric(5,2) CHECK (weight_kg IS NULL OR weight_kg > 0),
  body_fat_pct   numeric(4,1) CHECK (body_fat_pct IS NULL OR (body_fat_pct >= 0 AND body_fat_pct <= 100)),
  chest_cm       integer    CHECK (chest_cm IS NULL OR chest_cm > 0),
  waist_cm       integer    CHECK (waist_cm IS NULL OR waist_cm > 0),
  hips_cm        integer    CHECK (hips_cm IS NULL OR hips_cm > 0),
  notes          text       CHECK (notes IS NULL OR char_length(notes) <= 500),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE measurement_sharing (
  client_user_id  bigint NOT NULL,
  trainer_user_id bigint NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (client_user_id, trainer_user_id)
);

CREATE INDEX trainer_profile_user_id_idx            ON trainer_profile(user_id);
CREATE INDEX trainer_sport_sport_type_id_idx        ON trainer_sport(sport_type_id);
CREATE INDEX measurement_user_id_measured_at_idx    ON measurement(user_id, measured_at DESC);
CREATE INDEX measurement_sharing_client_idx         ON measurement_sharing(client_user_id);

INSERT INTO sport_type (sport_type_id, name)
VALUES
  (3001, 'Бег'),
  (3002, 'Плавание'),
  (3003, 'Йога'),
  (3004, 'Велоспорт'),
  (3005, 'Бокс'),
  (3006, 'Силовые тренировки'),
  (3007, 'Функциональный тренинг'),
  (3008, 'Растяжка');

SELECT setval(
  pg_get_serial_sequence('sport_type', 'sport_type_id'),
  (SELECT GREATEST(COALESCE(MAX(sport_type_id), 1), 3008) FROM sport_type),
  true
);

INSERT INTO profile (user_id, username, first_name, last_name, bio, avatar_url, is_trainer)
VALUES
  (1001, 'coach_anna',      'Анна',   'Петрова',   'Тренер по бегу и ОФП. Помогаю готовиться к забегам 10K, полумарафону и первому марафону без травм.',       NULL, true),
  (1002, 'runner_ivan',     'Иван',   'Сидоров',   'Любитель бега. Ищу тренера и собираю программу подготовки к первому полумарафону.',                        NULL, false),
  (1003, 'swim_mike',       'Михаил', 'Волков',    'Тренер по плаванию. Работаю с техникой дыхания, постановкой гребка и выносливостью.',                     NULL, true),
  (1004, 'yoga_elena',      'Елена',  'Смирнова',  'Инструктор по йоге и мягкой растяжке. Подходит для новичков, восстановления и работы со спиной.',         NULL, true),
  (1005, 'box_sergey',      'Сергей', 'Орлов',     'Тренер по боксу. Ставлю технику ударов, работу ног, защиту и безопасные спарринги.',                      NULL, true),
  (1006, 'fit_olga',        'Ольга',  'Кузнецова', 'Тренер по силовым и функциональным тренировкам. Делаю программы для дома и зала.',                        NULL, true),
  (1007, 'cycle_dima',      'Дмитрий','Морозов',   'Тренер по велоспорту. Помогаю развивать выносливость, каденс и готовиться к длинным заездам.',             NULL, true),
  (1008, 'client_maria',    'Мария',  'Федорова',  'Хочу вернуться к регулярным тренировкам после перерыва.',                                                  NULL, false),
  (1009, 'client_pavel',    'Павел',  'Никитин',   'Начинаю заниматься спортом и выбираю тренера для системной работы.',                                       NULL, false),
  (1010, 'admin_sporttech', 'Админ',  'SPORTtech', 'Технический аккаунт администратора.',                                                                      NULL, false);

INSERT INTO trainer_profile (user_id, education_degree, career_since_date)
VALUES
  (1001, 'Магистр физической культуры',              DATE '2018-09-01'),
  (1003, 'КМС по плаванию',                          DATE '2017-05-15'),
  (1004, 'Сертифицированный инструктор хатха-йоги',  DATE '2019-03-10'),
  (1005, 'МС по боксу',                              DATE '2016-02-01'),
  (1006, 'Специалист по физической подготовке',      DATE '2020-01-20'),
  (1007, 'Тренер по циклическим видам спорта',       DATE '2018-04-12');

INSERT INTO trainer_sport (user_id, sport_type_id, experience_years, sports_rank)
VALUES
  (1001, 3001, 7, 'КМС'),
  (1001, 3004, 4, NULL),
  (1003, 3002, 9, 'КМС'),
  (1003, 3006, 5, NULL),
  (1004, 3003, 6, NULL),
  (1004, 3008, 5, NULL),
  (1005, 3005, 10, 'МС'),
  (1005, 3007, 6, NULL),
  (1006, 3006, 8, NULL),
  (1006, 3007, 7, NULL),
  (1007, 3004, 8, 'КМС'),
  (1007, 3001, 5, NULL);

INSERT INTO measurement (measurement_id, user_id, measured_at, weight_kg, body_fat_pct, chest_cm, waist_cm, hips_cm, notes)
VALUES
  (2701, 1002, '2026-03-01', 78.50, 18.5, 96, 84, 96, 'Начало тренировок. Цель — подготовка к полумарафону.'),
  (2702, 1002, '2026-04-01', 77.20, 17.8, 96, 82, 95, 'Месяц по плану Анны. Бегаю три раза в неделю, самочувствие хорошее.'),
  (2703, 1002, '2026-05-01', 75.80, 17.0, 95, 80, 94, 'Вес снижается, выносливость растёт. Длинная уже 16 км без остановок.'),
  (2704, 1008, '2026-03-15', 62.00, 24.0, 88, 72, 98, 'Первый замер. Начинаю заниматься после долгого перерыва.'),
  (2705, 1008, '2026-04-15', 61.30, 23.2, 88, 71, 97, 'Йога и домашние силовые. Спина болит меньше, стала спокойнее сплю.'),
  (2706, 1008, '2026-05-15', 60.50, 22.5, 87, 70, 96, 'Продолжаю. Чувствую себя лучше, чем за последние два года.'),
  (2707, 1009, '2026-04-01', 85.00, 22.0, 102, 92, 102, 'Начало. Хочу сбросить 5 кг и укрепить корпус.'),
  (2708, 1009, '2026-05-01', 83.70, 21.3, 101, 90, 101, 'Месяц занятий с Сергеем. Минус 1.3 кг, плечи стали плотнее.');

SELECT setval(
  pg_get_serial_sequence('measurement', 'measurement_id'),
  (SELECT GREATEST(COALESCE(MAX(measurement_id), 1), 2708) FROM measurement),
  true
);

INSERT INTO measurement_sharing (client_user_id, trainer_user_id)
VALUES
  (1002, 1001),
  (1008, 1004);

CREATE TABLE goose_db_version (
  id         bigserial NOT NULL PRIMARY KEY,
  version_id bigint    NOT NULL,
  is_applied boolean   NOT NULL,
  tstamp     timestamp DEFAULT now()
);

INSERT INTO goose_db_version (version_id, is_applied) VALUES
  (0, true),
  (1, true),
  (2, true),
  (3, true),
  (4, true),
  (5, true),
  (6, true);

\connect sporttech_content

CREATE TYPE content_block_kind AS ENUM ('text', 'image', 'video', 'document');

CREATE TABLE content_post (
  post_id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_user_id               bigint NOT NULL,
  title                        text   NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
  required_subscription_level  integer CHECK (required_subscription_level IS NULL OR required_subscription_level >= 1),
  sport_type_id                bigint,
  created_at                   timestamptz NOT NULL DEFAULT now(),
  updated_at                   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE content_post_block (
  post_block_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id       bigint               NOT NULL REFERENCES content_post(post_id) ON DELETE CASCADE,
  position      integer              NOT NULL CHECK (position >= 0),
  kind          content_block_kind   NOT NULL,
  text_content  text,
  file_url      text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT content_post_block_position_key UNIQUE (post_id, position),
  CONSTRAINT content_post_block_payload_check CHECK (
    (kind = 'text'  AND text_content IS NOT NULL AND file_url IS NULL)
    OR
    (kind IN ('image', 'video', 'document') AND text_content IS NULL AND file_url IS NOT NULL)
  )
);

CREATE TABLE content_comment (
  comment_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id        bigint NOT NULL REFERENCES content_post(post_id) ON DELETE CASCADE,
  author_user_id bigint NOT NULL,
  body           text   NOT NULL CHECK (char_length(body) BETWEEN 1 AND 2000),
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE content_post_like (
  post_id    bigint NOT NULL REFERENCES content_post(post_id) ON DELETE CASCADE,
  user_id    bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (post_id, user_id)
);

CREATE TABLE content_subscription_tier (
  trainer_user_id bigint  NOT NULL,
  tier_id         integer NOT NULL CHECK (tier_id >= 1),
  name            text    NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
  price           integer NOT NULL CHECK (price >= 0),
  description     text    CHECK (description IS NULL OR char_length(description) <= 500),
  chat_enabled    boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  PRIMARY KEY (trainer_user_id, tier_id)
);

ALTER TABLE content_post
  ADD CONSTRAINT content_post_required_subscription_tier_fkey
  FOREIGN KEY (author_user_id, required_subscription_level)
  REFERENCES content_subscription_tier(trainer_user_id, tier_id);

CREATE TABLE content_subscription (
  subscription_id bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_user_id  bigint  NOT NULL,
  trainer_user_id bigint  NOT NULL,
  tier_id         integer NOT NULL,
  active          boolean NOT NULL DEFAULT true,
  expires_at      timestamptz NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT content_subscription_not_self_check CHECK (client_user_id <> trainer_user_id),
  CONSTRAINT content_subscription_tier_fkey
    FOREIGN KEY (trainer_user_id, tier_id)
    REFERENCES content_subscription_tier(trainer_user_id, tier_id)
);

CREATE TABLE content_donation (
  donation_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id     bigint  NOT NULL,
  recipient_user_id  bigint  NOT NULL,
  amount_value       integer NOT NULL CHECK (amount_value > 0),
  currency           text    NOT NULL CHECK (currency IN ('RUB')),
  message            text    CHECK (message IS NULL OR char_length(message) <= 500),
  created_at         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT content_donation_not_self_check CHECK (sender_user_id <> recipient_user_id)
);

CREATE TABLE content_notification (
  notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         bigint NOT NULL,
  type            text   NOT NULL CHECK (type IN ('comment', 'donation', 'like', 'post', 'subscription')),
  actor_user_id   bigint NOT NULL,
  title           text   NOT NULL CHECK (char_length(title) BETWEEN 1 AND 200),
  body            text   NOT NULL CHECK (char_length(body)  BETWEEN 1 AND 1000),
  post_id         bigint REFERENCES content_post(post_id)         ON DELETE CASCADE,
  comment_id      bigint REFERENCES content_comment(comment_id)   ON DELETE CASCADE,
  donation_id     bigint REFERENCES content_donation(donation_id) ON DELETE CASCADE,
  subscription_id bigint REFERENCES content_subscription(subscription_id) ON DELETE CASCADE,
  read_at         timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE content_payment (
  payment_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider            text   NOT NULL CHECK (provider IN ('stripe')),
  provider_payment_id text   UNIQUE,
  status              text   NOT NULL CHECK (status IN ('pending', 'confirmed')),
  sender_user_id      bigint  NOT NULL,
  recipient_user_id   bigint  NOT NULL,
  amount_value        integer NOT NULL CHECK (amount_value > 0),
  currency            text    NOT NULL CHECK (currency IN ('RUB')),
  message             text    CHECK (message IS NULL OR char_length(message) <= 500),
  confirmation_token  text    NOT NULL UNIQUE,
  confirmation_url    text,
  tier_id             bigint,
  donation_id         bigint  UNIQUE REFERENCES content_donation(donation_id),
  subscription_id     bigint  REFERENCES content_subscription(subscription_id),
  confirmed_at        timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT content_payment_not_self_check CHECK (sender_user_id <> recipient_user_id)
);

CREATE TABLE content_chat_message (
  message_id       bigserial PRIMARY KEY,
  sender_user_id   bigint NOT NULL,
  receiver_user_id bigint NOT NULL,
  body             text   NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
  created_at       timestamptz NOT NULL DEFAULT now(),
  is_read          boolean NOT NULL DEFAULT false
);

CREATE INDEX content_post_author_created_idx
  ON content_post(author_user_id, created_at DESC, post_id DESC);
CREATE INDEX content_post_sport_type_id_idx
  ON content_post(sport_type_id);
CREATE INDEX content_post_block_post_position_idx
  ON content_post_block(post_id, position);
CREATE INDEX content_comment_post_created_idx
  ON content_comment(post_id, created_at ASC, comment_id ASC);
CREATE INDEX content_post_like_post_idx
  ON content_post_like(post_id);
CREATE UNIQUE INDEX content_subscription_active_pair_idx
  ON content_subscription(client_user_id, trainer_user_id)
  WHERE active;
CREATE INDEX content_subscription_client_idx
  ON content_subscription(client_user_id, active, expires_at DESC);
CREATE INDEX content_subscription_trainer_idx
  ON content_subscription(trainer_user_id, tier_id);
CREATE INDEX content_donation_recipient_created_idx
  ON content_donation(recipient_user_id, created_at DESC, donation_id DESC);
CREATE INDEX content_notification_user_created_idx
  ON content_notification(user_id, created_at DESC, notification_id DESC);
CREATE INDEX content_notification_user_unread_idx
  ON content_notification(user_id, created_at DESC, notification_id DESC)
  WHERE read_at IS NULL;
CREATE UNIQUE INDEX content_notification_like_unique_idx
  ON content_notification(user_id, actor_user_id, post_id)
  WHERE type = 'like' AND post_id IS NOT NULL;
CREATE INDEX content_payment_sender_created_idx
  ON content_payment(sender_user_id, created_at DESC, payment_id DESC);
CREATE INDEX content_payment_recipient_created_idx
  ON content_payment(recipient_user_id, created_at DESC, payment_id DESC);
CREATE INDEX content_chat_message_conversation_idx
  ON content_chat_message (
    LEAST(sender_user_id, receiver_user_id),
    GREATEST(sender_user_id, receiver_user_id),
    created_at DESC
  );
CREATE INDEX content_chat_message_receiver_unread_idx
  ON content_chat_message(receiver_user_id, is_read)
  WHERE is_read = false;

INSERT INTO content_subscription_tier (trainer_user_id, tier_id, name, price, description, chat_enabled)
VALUES
  (1001, 1, 'Базовый',        500,  'Доступ к открытым тренировочным материалам и базовым планам.',          false),
  (1001, 2, 'Продвинутый',   1500,  'Закрытые темповые тренировки, недельные планы и разбор нагрузки.',      true),
  (1003, 1, 'Базовый',        600,  'Материалы по технике плавания и дыханию.',                              false),
  (1004, 1, 'Базовый',        400,  'Короткие комплексы йоги для ежедневной практики.',                      false),
  (1004, 2, 'Глубокая практика', 1200, 'Закрытые комплексы растяжки и восстановления.',                     true),
  (1005, 1, 'Базовый',        700,  'Базовая техника бокса и работа ног.',                                   false),
  (1005, 2, 'Спарринг',      1400,  'Расширенные упражнения для защиты и контратак.',                        false),
  (1005, 3, 'Премиум',       2200,  'Подробные закрытые разборы защитных действий.',                         true),
  (1006, 1, 'Базовый',        500,  'Домашние силовые тренировки без инвентаря.',                            false),
  (1006, 2, 'Прогрессия',    1300,  'Закрытые программы прогрессии и контроля нагрузки.',                   true),
  (1007, 1, 'Базовый',        600,  'Материалы по технике велотренировок.',                                  false),
  (1007, 2, 'План подготовки',1500, 'Закрытые месячные планы велоподготовки.',                               true);

INSERT INTO content_post (post_id, author_user_id, title, required_subscription_level, sport_type_id)
VALUES
  (2001, 1001, 'План подготовки к полумарафону',              NULL, 3001),
  (2002, 1001, 'Закрытая тренировка по темпу',                2,    3001),
  (2003, 1003, 'Техника дыхания в бассейне',                  NULL, 3002),
  (2004, 1004, 'Утренняя йога для спины',                     NULL, 3003),
  (2005, 1004, 'Закрытый комплекс глубокой растяжки',         2,    3003),
  (2006, 1005, 'Боксерская стойка и работа ног',              NULL, 3005),
  (2007, 1005, 'Разбор защитных действий для подписчиков',    3,    3005),
  (2008, 1006, 'Силовая тренировка дома без инвентаря',       NULL, 3006),
  (2009, 1006, 'Программа прогрессии в приседаниях',          2,    3006),
  (2010, 1007, 'Как держать ровный каденс на велосипеде',     NULL, 3004),
  (2011, 1007, 'План велоподготовки на месяц',                2,    3004);

SELECT setval(
  pg_get_serial_sequence('content_post', 'post_id'),
  (SELECT GREATEST(COALESCE(MAX(post_id), 1), 2011) FROM content_post),
  true
);

INSERT INTO content_post_block (post_block_id, post_id, position, kind, text_content, file_url)
VALUES
  (2101, 2001, 0, 'text',     'Начинаем с 3 беговых тренировок в неделю: легкий бег, интервалы и длинная тренировка.', NULL),
  (2102, 2001, 1, 'image',    NULL, 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5'),
  (2103, 2002, 0, 'text',     'Закрытый материал для подписчиков: разбор темповых интервалов и недельной нагрузки.', NULL),
  (2104, 2002, 1, 'document', NULL, 'https://example.com/docs/tempo-workout-plan.pdf'),
  (2105, 2003, 0, 'text',     'Главная ошибка новичков в бассейне — задержка выдоха под водой. Ниже короткая памятка.', NULL),
  (2106, 2003, 1, 'video',    NULL, 'https://example.com/videos/swim-breathing-drill.mp4'),
  (2107, 2001, 2, 'text',     'Если пульс растет слишком быстро, снижаем темп и оставляем запас на последнюю треть дистанции.', NULL),
  (2108, 2002, 2, 'text',     'Главное правило: темповая работа не должна превращаться в гонку на каждой тренировке.', NULL),
  (2109, 2003, 2, 'text',     'Попробуйте выдыхать спокойно в воду на 3-4 счета, а вдох делать коротким и без подъема головы.', NULL),
  (2110, 2004, 0, 'text',     'Пять минут мягкой разминки помогают убрать скованность после сна и подготовить спину к дню.', NULL),
  (2111, 2004, 1, 'image',    NULL, 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b'),
  (2112, 2004, 2, 'text',     'Двигайтесь без боли: кошка-корова, вытяжение в позе ребенка и легкие скручивания.', NULL),
  (2113, 2005, 0, 'text',     'Закрытый комплекс для подписчиков: глубокая растяжка задней поверхности бедра и грудного отдела.', NULL),
  (2114, 2005, 1, 'video',    NULL, 'https://example.com/videos/deep-stretching-flow.mp4'),
  (2115, 2005, 2, 'text',     'Каждое положение удерживаем 40-60 секунд, дыхание спокойное, без рывков.', NULL),
  (2116, 2006, 0, 'text',     'Начинаем с базовой стойки: подбородок ниже, локти ближе к корпусу, вес распределен мягко.', NULL),
  (2117, 2006, 1, 'image',    NULL, 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed'),
  (2118, 2006, 2, 'text',     'После стойки добавляем короткие шаги вперед-назад и в сторону, не скрещивая ноги.', NULL),
  (2119, 2007, 0, 'text',     'Премиум-разбор: уклоны, нырки и выходы из угла после атаки соперника.', NULL),
  (2120, 2007, 1, 'document', NULL, 'https://example.com/docs/boxing-defense-checklist.pdf'),
  (2121, 2007, 2, 'text',     'Отрабатывайте защиту сначала медленно, потом добавляйте скорость только без потери баланса.', NULL),
  (2122, 2008, 0, 'text',     'Эта тренировка подходит для дома: приседания, отжимания, ягодичный мост и планка.', NULL),
  (2123, 2008, 1, 'image',    NULL, 'https://images.unsplash.com/photo-1518611012118-696072aa579a'),
  (2124, 2008, 2, 'text',     'Сделайте 3 круга по 40 секунд работы и 20 секунд отдыха между упражнениями.', NULL),
  (2125, 2009, 0, 'text',     'Закрытая программа: как увеличить объем приседаний без перегруза коленей и поясницы.', NULL),
  (2126, 2009, 1, 'document', NULL, 'https://example.com/docs/squat-progression.pdf'),
  (2127, 2009, 2, 'text',     'Добавляйте нагрузку только если техника остается стабильной на последних повторениях.', NULL),
  (2128, 2010, 0, 'text',     'Ровный каденс помогает экономить силы на длинной дистанции и не забивать ноги на подъемах.', NULL),
  (2129, 2010, 1, 'image',    NULL, 'https://images.unsplash.com/photo-1485965120184-e220f721d03e'),
  (2130, 2010, 2, 'text',     'Начните с диапазона 80-90 оборотов в минуту и следите, чтобы дыхание оставалось контролируемым.', NULL),
  (2131, 2011, 0, 'text',     'План для подписчиков: четыре недели с постепенным ростом объема и одной восстановительной неделей.', NULL),
  (2132, 2011, 1, 'document', NULL, 'https://example.com/docs/cycling-month-plan.pdf'),
  (2133, 2011, 2, 'text',     'Не пропускайте легкие дни: именно на них организм адаптируется к нагрузке.', NULL);

SELECT setval(
  pg_get_serial_sequence('content_post_block', 'post_block_id'),
  (SELECT GREATEST(COALESCE(MAX(post_block_id), 1), 2133) FROM content_post_block),
  true
);

INSERT INTO content_post_like (post_id, user_id)
VALUES
  (2001, 1002),
  (2003, 1001),
  (2001, 1008),
  (2003, 1008),
  (2004, 1002),
  (2004, 1008),
  (2006, 1009),
  (2008, 1002),
  (2008, 1005),
  (2010, 1008),
  (2010, 1009);

INSERT INTO content_subscription (subscription_id, client_user_id, trainer_user_id, tier_id, active, expires_at)
VALUES
  (2401, 1002, 1001, 2, true, now() + INTERVAL '30 days'),
  (2402, 1008, 1004, 2, true, now() + INTERVAL '30 days'),
  (2403, 1009, 1005, 3, true, now() + INTERVAL '30 days');

SELECT setval(
  pg_get_serial_sequence('content_subscription', 'subscription_id'),
  (SELECT GREATEST(COALESCE(MAX(subscription_id), 1), 2403) FROM content_subscription),
  true
);

INSERT INTO content_comment (comment_id, post_id, author_user_id, body)
VALUES
  (2201, 2001, 1002, 'Спасибо за план! Начал с трёх тренировок в неделю, уже через две чувствую прогресс.'),
  (2202, 2001, 1008, 'Подскажите, как часто делать длинную тренировку в самом начале?'),
  (2203, 2001, 1001, 'Мария, в первые две недели — раз в неделю, не больше 70–80% от целевого темпа. Главное — не торопиться.'),
  (2204, 2003, 1009, 'Попробовал методику дыхания — стало намного комфортнее в воде. Раньше задерживал дыхание и уставал быстро.'),
  (2205, 2003, 1001, 'Главное — не форсировать, тело само подстраивается за несколько тренировок.'),
  (2206, 2004, 1008, 'Утренний комплекс просто спасение для спины. Делаю уже неделю — чувствую ощутимую разницу.'),
  (2207, 2004, 1002, 'Попробовал кошку-корову после длинной пробежки — спина расслабляется лучше, чем от простой растяжки.'),
  (2208, 2006, 1009, 'Стойка стала намного устойчивее. Теперь понимаю, почему локти так важны — сразу уменьшилась нагрузка на плечи.'),
  (2209, 2008, 1002, 'Сделал три круга по схеме 40/20 — отличная нагрузка, инвентарь не нужен.'),
  (2210, 2010, 1008, 'Держать 85 оборотов в минуту оказалось сложнее, чем казалось. Буду тренироваться с метрономом.'),
  (2211, 2010, 1009, 'После третьей тренировки каденс стал ровнее, дыхание тоже улучшилось.');

SELECT setval(
  pg_get_serial_sequence('content_comment', 'comment_id'),
  (SELECT GREATEST(COALESCE(MAX(comment_id), 1), 2211) FROM content_comment),
  true
);

INSERT INTO content_donation (donation_id, sender_user_id, recipient_user_id, amount_value, currency, message)
VALUES
  (2301, 1002, 1001, 300, 'RUB', 'Анна, отличные материалы по подготовке — спасибо!'),
  (2302, 1008, 1004, 250, 'RUB', 'Елена, комплекс йоги реально помог со спиной.'),
  (2303, 1009, 1005, 500, 'RUB', 'Сергей, лучшее объяснение стойки, что видел — спасибо!'),
  (2304, 1008, 1006, 200, 'RUB', 'Ольга, домашняя тренировка зашла на ура, уже третий раз делаю.');

SELECT setval(
  pg_get_serial_sequence('content_donation', 'donation_id'),
  (SELECT GREATEST(COALESCE(MAX(donation_id), 1), 2304) FROM content_donation),
  true
);

INSERT INTO content_notification
  (notification_id, user_id, type, actor_user_id, title, body,
   post_id, comment_id, donation_id, subscription_id, read_at)
VALUES
  (2501, 1001, 'subscription', 1002, 'Новый подписчик',
   'Иван Сидоров оформил подписку «Продвинутый».',
   NULL, NULL, NULL, 2401, now() - INTERVAL '25 days'),
  (2502, 1004, 'subscription', 1008, 'Новый подписчик',
   'Мария Федорова оформила подписку «Глубокая практика».',
   NULL, NULL, NULL, 2402, now() - INTERVAL '20 days'),
  (2503, 1005, 'subscription', 1009, 'Новый подписчик',
   'Павел Никитин оформил подписку «Премиум».',
   NULL, NULL, NULL, 2403, now() - INTERVAL '15 days'),
  (2504, 1001, 'like', 1008, 'Новый лайк',
   'Мария Федорова оценила ваш пост «План подготовки к полумарафону».',
   2001, NULL, NULL, NULL, now() - INTERVAL '10 days'),
  (2505, 1003, 'like', 1008, 'Новый лайк',
   'Мария Федорова оценила ваш пост «Техника дыхания в бассейне».',
   2003, NULL, NULL, NULL, NULL),
  (2506, 1004, 'like', 1002, 'Новый лайк',
   'Иван Сидоров оценил ваш пост «Утренняя йога для спины».',
   2004, NULL, NULL, NULL, NULL),
  (2507, 1006, 'like', 1005, 'Новый лайк',
   'Сергей Орлов оценил ваш пост «Силовая тренировка дома без инвентаря».',
   2008, NULL, NULL, NULL, NULL),
  (2508, 1007, 'like', 1008, 'Новый лайк',
   'Мария Федорова оценила ваш пост «Как держать ровный каденс на велосипеде».',
   2010, NULL, NULL, NULL, NULL),
  (2509, 1007, 'like', 1009, 'Новый лайк',
   'Павел Никитин оценил ваш пост «Как держать ровный каденс на велосипеде».',
   2010, NULL, NULL, NULL, NULL),
  (2510, 1001, 'comment', 1008, 'Новый комментарий',
   'Мария Федорова спросила: «Как часто делать длинную тренировку в самом начале?»',
   2001, 2202, NULL, NULL, NULL),
  (2511, 1001, 'comment', 1002, 'Новый комментарий',
   'Иван Сидоров написал: «Спасибо за план! Начал с трёх тренировок, уже вижу прогресс.»',
   2001, 2201, NULL, NULL, now() - INTERVAL '5 days'),
  (2512, 1004, 'comment', 1008, 'Новый комментарий',
   'Мария Федорова написала: «Утренний комплекс просто спасение для спины.»',
   2004, 2206, NULL, NULL, now() - INTERVAL '3 days'),
  (2513, 1005, 'comment', 1009, 'Новый комментарий',
   'Павел Никитин написал: «Стойка стала намного устойчивее.»',
   2006, 2208, NULL, NULL, NULL),
  (2514, 1006, 'comment', 1002, 'Новый комментарий',
   'Иван Сидоров написал: «Сделал три круга по схеме 40/20 — отличная нагрузка.»',
   2008, 2209, NULL, NULL, NULL),
  (2515, 1001, 'donation', 1002, 'Новый донат',
   'Иван Сидоров отправил 300 ₽: «Анна, отличные материалы по подготовке — спасибо!»',
   NULL, NULL, 2301, NULL, now() - INTERVAL '8 days'),
  (2516, 1004, 'donation', 1008, 'Новый донат',
   'Мария Федорова отправила 250 ₽: «Елена, комплекс йоги реально помог со спиной.»',
   NULL, NULL, 2302, NULL, NULL),
  (2517, 1005, 'donation', 1009, 'Новый донат',
   'Павел Никитин отправил 500 ₽: «Сергей, лучшее объяснение стойки, что видел!»',
   NULL, NULL, 2303, NULL, NULL),
  (2518, 1006, 'donation', 1008, 'Новый донат',
   'Мария Федорова отправила 200 ₽: «Ольга, домашняя тренировка зашла на ура.»',
   NULL, NULL, 2304, NULL, NULL),
  (2519, 1002, 'post', 1001, 'Новый пост от тренера',
   'Анна Петрова опубликовала: «Закрытая тренировка по темпу».',
   2002, NULL, NULL, NULL, now() - INTERVAL '18 days'),
  (2520, 1008, 'post', 1004, 'Новый пост от тренера',
   'Елена Смирнова опубликовала: «Закрытый комплекс глубокой растяжки».',
   2005, NULL, NULL, NULL, NULL),
  (2521, 1009, 'post', 1005, 'Новый пост от тренера',
   'Сергей Орлов опубликовал: «Разбор защитных действий для подписчиков».',
   2007, NULL, NULL, NULL, NULL);

SELECT setval(
  pg_get_serial_sequence('content_notification', 'notification_id'),
  (SELECT GREATEST(COALESCE(MAX(notification_id), 1), 2521) FROM content_notification),
  true
);

INSERT INTO content_chat_message (message_id, sender_user_id, receiver_user_id, body, is_read)
VALUES
  (2601, 1002, 1001, 'Анна, добрый день! Хотел спросить про темп на длинной тренировке — насколько можно разгоняться?', true),
  (2602, 1001, 1002, 'Иван, привет! На длинных держите «разговорный» темп — должны уметь говорить короткими фразами. Ориентир — пульс 130–145 уд/мин.', true),
  (2603, 1002, 1001, 'Понял, спасибо! Попробую в воскресенье. Пульсометра нет, ориентируюсь на дыхание.', true),
  (2604, 1001, 1002, 'Дыхание — отличный ориентир. Если можете считать до 4 на выдох — темп правильный. Удачи в воскресенье!', false),
  (2605, 1008, 1004, 'Елена, здравствуйте! Можно ли делать ваш утренний комплекс каждый день?', true),
  (2606, 1004, 1008, 'Мария, привет! Да, утренний комплекс можно ежедневно — он мягкий. Главное, не через боль.', true),
  (2607, 1008, 1004, 'Отлично, буду делать каждое утро. Спину уже меньше тянет после первой недели.', true),
  (2608, 1004, 1008, 'Это хороший знак! Если будет дискомфорт в каком-то упражнении — пишите, подберём замену.', false),
  (2609, 1009, 1005, 'Сергей, привет! Как часто можно отрабатывать защиту — каждый день или нужны дни отдыха?', true),
  (2610, 1005, 1009, 'Павел, привет! Технические упражнения без контакта — можно каждый день. Спарринги — не чаще 2–3 раз в неделю.', true),
  (2611, 1009, 1005, 'Понял. Пока без спаррингов, ставлю технику. На этой неделе отработал уклоны по вашему разбору.', true),
  (2612, 1005, 1009, 'Отлично! Снимите видео на следующей тренировке — посмотрю и дам обратную связь.', false);

SELECT setval(
  pg_get_serial_sequence('content_chat_message', 'message_id'),
  (SELECT GREATEST(COALESCE(MAX(message_id), 1), 2612) FROM content_chat_message),
  true
);

CREATE TABLE goose_db_version (
  id         bigserial NOT NULL PRIMARY KEY,
  version_id bigint    NOT NULL,
  is_applied boolean   NOT NULL,
  tstamp     timestamp DEFAULT now()
);

INSERT INTO goose_db_version (version_id, is_applied) VALUES
  (0,  true),
  (1,  true),
  (2,  true),
  (3,  true),
  (4,  true),
  (5,  true),
  (6,  true),
  (7,  true),
  (8,  true),
  (9,  true),
  (10, true),
  (11, true),
  (12, true),
  (13, true),
  (14, true),
  (15, true);
