package domain

import "errors"

var (
	ErrPostNotFound             = errors.New("post not found")
	ErrPostForbidden            = errors.New("post forbidden")
	ErrCommentNotFound          = errors.New("comment not found")
	ErrCommentForbidden         = errors.New("comment can only be modified by its author")
	ErrCommentEditWindowExpired = errors.New("comment edit window has expired")
	ErrSubscriptionTierNotFound = errors.New("subscription tier not found")
	ErrSubscriptionTierInUse    = errors.New("subscription tier is in use")
	ErrSubscriptionNotFound     = errors.New("subscription not found")
	ErrDonationNotFound         = errors.New("donation not found")
	ErrPaymentNotFound          = errors.New("payment not found")
	ErrPaymentAlreadyConfirmed  = errors.New("payment already confirmed")
	ErrPaymentForbidden         = errors.New("payment forbidden")
	ErrPaymentTokenMismatch     = errors.New("payment confirmation token mismatch")
	ErrNotificationNotFound     = errors.New("notification not found")
	ErrInvalidBlockKind         = errors.New("invalid block kind")
	ErrInvalidBlockData         = errors.New("invalid block data")
	ErrChatAccessForbidden      = errors.New("chat access forbidden: no active chat-enabled subscription")
	ErrChatMessageNotFound      = errors.New("chat message not found")
	ErrMeetingAccessForbidden   = errors.New("meeting access forbidden: no active calendar-enabled subscription")
	ErrMeetingRuleNotFound      = errors.New("meeting availability rule not found")
	ErrMeetingSlotNotFound      = errors.New("meeting slot not found")
	ErrMeetingBookingNotFound   = errors.New("meeting booking not found")
	ErrMeetingSlotUnavailable   = errors.New("meeting slot is not available")
	ErrMeetingSlotTaken         = errors.New("meeting slot overlaps an existing booking")
	ErrMeetingClientLimit       = errors.New("client already has an active booking with this trainer")
	ErrMeetingNotCancelable     = errors.New("meeting booking cannot be cancelled")
)
