// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package httpgateway

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD31a5a85DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(in *jlexer.Lexer, out *errorEnvelope) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Error).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD31a5a85EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(out *jwriter.Writer, in errorEnvelope) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		(in.Error).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v errorEnvelope) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD31a5a85EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v errorEnvelope) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD31a5a85EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *errorEnvelope) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD31a5a85DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *errorEnvelope) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD31a5a85DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(l, v)
}
func easyjsonD31a5a85DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(in *jlexer.Lexer, out *errorBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD31a5a85EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(out *jwriter.Writer, in errorBody) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v errorBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD31a5a85EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v errorBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD31a5a85EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *errorBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD31a5a85DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *errorBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD31a5a85DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(l, v)
}
