// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package httpgateway

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE880d261DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(in *jlexer.Lexer, out *sseConversationsSnapshot) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "conversations":
			if in.IsNull() {
				in.Skip()
				out.Conversations = nil
			} else {
				in.Delim('[')
				if out.Conversations == nil {
					if !in.IsDelim(']') {
						out.Conversations = make([]sseConversationPayload, 0, 2)
					} else {
						out.Conversations = []sseConversationPayload{}
					}
				} else {
					out.Conversations = (out.Conversations)[:0]
				}
				for !in.IsDelim(']') {
					var v1 sseConversationPayload
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Conversations = append(out.Conversations, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "unread_total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnreadTotal = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE880d261EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(out *jwriter.Writer, in sseConversationsSnapshot) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"conversations\":"
		out.RawString(prefix[1:])
		if in.Conversations == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Conversations {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"unread_total\":"
		out.RawString(prefix)
		out.Int32(int32(in.UnreadTotal))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v sseConversationsSnapshot) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE880d261EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v sseConversationsSnapshot) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE880d261EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *sseConversationsSnapshot) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE880d261DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *sseConversationsSnapshot) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE880d261DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(l, v)
}
func easyjsonE880d261DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(in *jlexer.Lexer, out *sseConversationPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "other_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OtherUserID = int64(in.Int64())
			}
		case "last_message":
			if in.IsNull() {
				in.Skip()
				out.LastMessage = nil
			} else {
				if out.LastMessage == nil {
					out.LastMessage = new(sseChatMessagePayload)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.LastMessage).UnmarshalEasyJSON(in)
				}
			}
		case "unread_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnreadCount = int32(in.Int32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE880d261EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(out *jwriter.Writer, in sseConversationPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"other_user_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.OtherUserID))
	}
	{
		const prefix string = ",\"last_message\":"
		out.RawString(prefix)
		if in.LastMessage == nil {
			out.RawString("null")
		} else {
			(*in.LastMessage).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"unread_count\":"
		out.RawString(prefix)
		out.Int32(int32(in.UnreadCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v sseConversationPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE880d261EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v sseConversationPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE880d261EncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *sseConversationPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE880d261DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *sseConversationPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE880d261DecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(l, v)
}
