// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package httpgateway

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9e23f49cDecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(in *jlexer.Lexer, out *sseChatReadPayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message_ids":
			if in.IsNull() {
				in.Skip()
				out.MessageIDs = nil
			} else {
				in.Delim('[')
				if out.MessageIDs == nil {
					if !in.IsDelim(']') {
						out.MessageIDs = make([]int64, 0, 8)
					} else {
						out.MessageIDs = []int64{}
					}
				} else {
					out.MessageIDs = (out.MessageIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int64(in.Int64())
					}
					out.MessageIDs = append(out.MessageIDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e23f49cEncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(out *jwriter.Writer, in sseChatReadPayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message_ids\":"
		out.RawString(prefix[1:])
		if in.MessageIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.MessageIDs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int64(int64(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v sseChatReadPayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e23f49cEncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v sseChatReadPayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e23f49cEncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *sseChatReadPayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e23f49cDecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *sseChatReadPayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e23f49cDecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway(l, v)
}
func easyjson9e23f49cDecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(in *jlexer.Lexer, out *sseChatMessagePayload) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageID = int64(in.Int64())
			}
		case "sender_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SenderUserID = int64(in.Int64())
			}
		case "receiver_user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReceiverUserID = int64(in.Int64())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "is_read":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsRead = bool(in.Bool())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9e23f49cEncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(out *jwriter.Writer, in sseChatMessagePayload) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message_id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.MessageID))
	}
	{
		const prefix string = ",\"sender_user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.SenderUserID))
	}
	{
		const prefix string = ",\"receiver_user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReceiverUserID))
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	{
		const prefix string = ",\"is_read\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsRead))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v sseChatMessagePayload) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9e23f49cEncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v sseChatMessagePayload) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9e23f49cEncodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *sseChatMessagePayload) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9e23f49cDecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *sseChatMessagePayload) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9e23f49cDecodeGithubComGoParkMailRu20261SPORTTechServicesApiGatewayInternalInfrastructureHttpgateway1(l, v)
}
