service_name: profile-service

server:
  host: 0.0.0.0
  grpc_port: "9092"
  http_port: "8082"
  shutdown_timeout: 10s

postgres:
  host: localhost
  port: "5432"
  db_name: sporttech_profile
  application_name: profile-service
  db_max_open_conns: 12
  db_max_idle_conns: 6
  db_conn_max_lifetime: 30m
  db_connect_timeout_seconds: 5
  db_statement_timeout: 5s
  db_lock_timeout: 1s
  db_idle_in_transaction_session_timeout: 10s

storage:
  host: localhost
  port: "8000"
  bucket: avatars
  public_base_url: http://localhost:8000/avatars
  use_ssl: false

openapi:
  file_path: grpc/gen/openapiv2/profile/v1/profile.swagger.json
