package postgres_test

import (
	"context"
	"database/sql"
	"os"
	"testing"
	"time"

	"github.com/go-park-mail-ru/2026_1_SPORT.tech/services/auth/internal/adapters/repository/postgres"
	"github.com/go-park-mail-ru/2026_1_SPORT.tech/services/auth/internal/domain"
	"github.com/go-park-mail-ru/2026_1_SPORT.tech/services/auth/internal/usecase"
	_ "github.com/lib/pq"
)

const repositorySchemaSQL = `
DROP TABLE IF EXISTS auth_session;
DROP TABLE IF EXISTS auth_user;

CREATE TABLE auth_user (
	user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email text NOT NULL,
	username text NOT NULL,
	password_hash text NOT NULL,
	role text NOT NULL,
	status text NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT auth_user_email_key UNIQUE (email),
	CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE auth_session (
	session_id_hash text PRIMARY KEY,
	user_id bigint NOT NULL REFERENCES auth_user(user_id) ON DELETE CASCADE,
	expires_at timestamptz NOT NULL,
	revoked_at timestamptz,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL
);
`

func TestRepositoriesIntegration(t *testing.T) {
	dsn := os.Getenv("AUTH_TEST_DATABASE_DSN")
	if dsn == "" {
		t.Skip("AUTH_TEST_DATABASE_DSN is not set")
	}

	db, err := sql.Open("postgres", dsn)
	if err != nil {
		t.Fatalf("open database: %v", err)
	}
	defer db.Close()

	if _, err := db.Exec(repositorySchemaSQL); err != nil {
		t.Fatalf("apply schema: %v", err)
	}

	accountRepository := postgres.NewAccountRepository(db)
	sessionRepository := postgres.NewSessionRepository(db)
	now := time.Date(2026, time.April, 18, 12, 0, 0, 0, time.UTC)

	account, err := accountRepository.Create(context.Background(), usecase.CreateAccountParams{
		Email:        "john@example.com",
		Username:     "john_doe",
		PasswordHash: "hashed-password",
		Role:         domain.RoleClient,
		Status:       domain.StatusActive,
		Now:          now,
	})
	if err != nil {
		t.Fatalf("create account: %v", err)
	}

	loadedAccount, err := accountRepository.GetByEmail(context.Background(), "john@example.com")
	if err != nil {
		t.Fatalf("get account by email: %v", err)
	}
	if loadedAccount.ID != account.ID {
		t.Fatalf("unexpected account id: got %d, want %d", loadedAccount.ID, account.ID)
	}

	session := domain.Session{
		IDHash:    "session-hash",
		UserID:    account.ID,
		ExpiresAt: now.Add(24 * time.Hour),
		CreatedAt: now,
		UpdatedAt: now,
	}
	if err := sessionRepository.Create(context.Background(), session); err != nil {
		t.Fatalf("create session: %v", err)
	}

	loadedSession, err := sessionRepository.GetByHash(context.Background(), "session-hash")
	if err != nil {
		t.Fatalf("get session by hash: %v", err)
	}
	if loadedSession.UserID != account.ID {
		t.Fatalf("unexpected session user id: got %d, want %d", loadedSession.UserID, account.ID)
	}
}
