-- +goose Up
CREATE TABLE auth_user (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL CHECK (char_length(email) <= 254),
  username text NOT NULL CHECK (username ~ '^[A-Za-z0-9_]{3,30}$'),
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('client', 'trainer', 'admin')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT auth_user_email_key UNIQUE (email),
  CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE auth_session (
  session_id_hash text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES auth_user(user_id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CHECK (expires_at > created_at)
);

CREATE INDEX auth_session_user_id_idx ON auth_session(user_id);
CREATE INDEX auth_session_expires_at_idx ON auth_session(expires_at);

-- +goose Down
DROP TABLE IF EXISTS auth_session;
DROP TABLE IF EXISTS auth_user;
