// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package yookassa

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa(in *jlexer.Lexer, out *paymentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "confirmation":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Confirmation).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa(out *jwriter.Writer, in paymentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"confirmation\":"
		out.RawString(prefix)
		(in.Confirmation).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v paymentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v paymentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *paymentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *paymentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa(l, v)
}
func easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa1(in *jlexer.Lexer, out *paymentConfirmation) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "return_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReturnURL = string(in.String())
			}
		case "confirmation_url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmationURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa1(out *jwriter.Writer, in paymentConfirmation) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	if in.ReturnURL != "" {
		const prefix string = ",\"return_url\":"
		out.RawString(prefix)
		out.String(string(in.ReturnURL))
	}
	if in.ConfirmationURL != "" {
		const prefix string = ",\"confirmation_url\":"
		out.RawString(prefix)
		out.String(string(in.ConfirmationURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v paymentConfirmation) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v paymentConfirmation) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *paymentConfirmation) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *paymentConfirmation) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa1(l, v)
}
func easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa2(in *jlexer.Lexer, out *paymentAmount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa2(out *jwriter.Writer, in paymentAmount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v paymentAmount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v paymentAmount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *paymentAmount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *paymentAmount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa2(l, v)
}
func easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa3(in *jlexer.Lexer, out *createPaymentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Amount).UnmarshalEasyJSON(in)
			}
		case "capture":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Capture = bool(in.Bool())
			}
		case "confirmation":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Confirmation).UnmarshalEasyJSON(in)
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa3(out *jwriter.Writer, in createPaymentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		(in.Amount).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"capture\":"
		out.RawString(prefix)
		out.Bool(bool(in.Capture))
	}
	{
		const prefix string = ",\"confirmation\":"
		out.RawString(prefix)
		(in.Confirmation).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v createPaymentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v createPaymentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8b11588aEncodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *createPaymentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *createPaymentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8b11588aDecodeGithubComGoParkMailRu20261SPORTTechServicesContentInternalAdaptersClientYookassa3(l, v)
}
